aws/amazon-ecs-cli

.travis.yml, Makefile, ecs-cli/modules/command/cluster_app_test.go, ecs-cli/modules/config/params_test.go, scripts/hack/symlink-gopath-travisci, scripts/shared_env
This adds a `.travis.yml` file and some misc things needed for it to work there.
One thing this added which shouldn't necessarily be there forever is the environment variables in the `make test` target. It would be better to not have such a dependency at all.
This also splits `generate` into a target which is not run every time in the interest of reducing dependencies when running tests and also in making the code-test-build cycle quicker.
Tested on my fork https://travis-ci.org/euank/amazon-ecs-cli
r? @samuelkarp @uttarasridhar
=> Add travis-ci testing

Makefile, scripts/stage.sh
With this change, release builds (using the release script) no longer appear dirty:
```
$ ./ecs-cli -v
ecs-cli version 0.1.0 (1bff41b)
```
r? @uttarasridhar @euank
=> Fix release builds appearing dirty

ecs-cli/modules/aws/clients/ecs/client.go, ecs-cli/modules/aws/clients/ecs/client_test.go, ecs-cli/modules/compose/ecs/utils/name.go
The hash for the task definition local cache now utilizes the region,
AWS account id and compose file. The CLI now checks to see if a task
definition is ACTIVE prior to using it, i.e. when pulling the definition
from the either the cache or from ECS.
Fixes #38 
@samuelkarp @euank @uttarasridhar
=> Include region, account id in key for local Task Definition cache

ecs-cli/modules/aws/clients/ecs/client.go
Fixed the logging of the Family name by dereferencing a pointer
correctly when calling RegisterTaskDefinition API.
Fixes #37
=> Adding better error messaging for RegisterTaskDefinition API

Makefile, ecs-cli/modules/command/cluster_app_test.go, ecs-cli/modules/compose/cli/ecs/app/factory_test.go, ecs-cli/modules/config/destination_test.go, ecs-cli/modules/config/params_test.go
Removing dependencies on environment variables which cause tests
to fail if environment variables are cleared(e.g via os.ClearEnv())
within the test cases.
@samuelkarp @euank @aaithal
=> Remove dependencies on environment variables for tests

ecs-cli/modules/command/configure.go, ecs-cli/modules/command/configure_test.go, ecs-cli/modules/config/config.go, ecs-cli/modules/config/config_test.go
This commit streamlines the logic for resolving AWS credentials.
The ecs-cli now attempts to resolve AWS credentials in the following
order: ENV variables, ECS Profile, AWS Profile and EC2 Instance role.
This commit also removes some unneccessary logic in the ecs-cli
configure command.
Fixes #35 
@samuelkarp @aaithal @euank @uttarasridhar
=> Change ordering of AWS Credential resolution for the ecs-cli

ecs-cli/modules/config/ami/ami.go
Sourced from http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
=> Update AMIs from 2015.09.c to 2015.09.d

ecs-cli/modules/aws/clients/cloudformation/template.go
Addresses issue #64. Got the updated instance types list from https://aws.amazon.com/ec2/instance-types/
=> Add support for t2.nano, g2 and d2 instance types

scripts/ec2-stage.sh
Removed --owner and --group flags for tar (not supported by POSIX standard https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/tar.1.html )
=> Fix ec2-stage script to run on Mac OS

Makefile, ecs-cli/license/generate_license.go, ecs-cli/license/license.go, ecs-cli/license/license_command.go, ecs-cli/license/license_test.go, ecs-cli/main.go, scripts/license.sh
$ make generate
. ./scripts/shared_env && go generate ./ecs-cli/license/... ./ecs-cli/modules/...
$ make test
. ./scripts/shared_env && env -i PATH=$PATH GOPATH=$GOPATH GOROOT=$GOROOT go test -timeout=120s -v -cover ./ecs-cli/license/... ./ecs-cli/modules/...
=== RUN   TestVendorDirectoryStructure
--- PASS: TestVendorDirectoryStructure (0.00s)
...
$ make build
Built ecs-cli
$ ./bin/local/ecs-cli license | less
Copyright 2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the
License. A copy of the License is located at
http://aws.amazon.com/apache2.0/
or in the "license" file accompanying this file. …
=> Add License file to the executable

ecs-cli/modules/config/ami/ami.go
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
=> Update the AMI ids to Amazon ECS-Optimized Amazon Linux AMI 2016.03.a

ecs-cli/modules/compose/cli/ecs/app/command.go, ecs-cli/modules/compose/cli/ecs/app/service_command.go, ecs-cli/modules/compose/ecs/context.go, ecs-cli/modules/compose/ecs/utils/convert_compose_yml.go, ecs-cli/modules/compose/ecs/utils/convert_compose_yml_test.go, ecs-cli/modules/compose/ecs/utils/convert_task_definition.go, ecs-cli/modules/compose/ecs/utils/convert_task_definition_test.go, ecs-cli/modules/compose/libcompose/merge.go, ecs-cli/modules/compose/libcompose/merge_test.go
Closes aws/amazon-ecs-cli#48.
$ cat docker-compose.yml 
rails:
...
environment:
- STAGE
***
$ export STAGE="development"
$ ./bin/local/ecs-cli compose service create
INFO[0000] Using ECS task definition                     TaskDefinition=ecscompose-amazon-ecs-cli:16
INFO[0000] Created an ECS Service                       serviceName=ecscompose-service-amazon-ecs-cli taskDefinition=ecscompose-amazon-ecs-cli:16
$ aws ecs --region us-west-2 describe-task-definition --task-definition ecscompose-amazon-ecs-cli:16
"environment": [
{
"name": "STAGE", 
"value": "development"
}
], 
***
UPDATED variable
$ export STAGE="testing"
$ ./bin/local/ecs-cli compose service up
INFO[0000] Using ECS task definition                     TaskDefinition=ecscompose-amazon-ecs-cli:17
INFO[0000] Updated the ECS …
=> Add support for compose option env_file. Also, support session environment variables.

ecs-cli/modules/config/aws_credentials_example.ini, ecs-cli/modules/config/config.go, ecs-cli/modules/config/config_test.go
Fixes aws/amazon-ecs-cli#105
$ make test
PASS
$ make build
Built ecs-cli
$ ./bin/local/ecs-cli configure -r us-west-2 -c local-test
INFO[0000] Saved ECS CLI configuration for cluster (local-test) 
$ ./bin/local/ecs-cli up --capability-iam --keypair test_key_pair
INFO[0000] Created cluster cluster=local-test
INFO[0000] Waiting for your cluster resources to be created 
INFO[0000] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
[ec2-user@ip-xx-x-x-xxx ~]$ sudo /usr/local/bin/ecs-cli up --capability-iam
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6e9b05]
goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMeta …
=> Add missing EC2MetadataClient to EC2RoleProvider

ecs-cli/modules/compose/cli/ecs/app/command.go, ecs-cli/modules/compose/ecs/context.go, ecs-cli/modules/compose/ecs/project.go, ecs-cli/modules/compose/ecs/project_test.go
closes aws/amazon-ecs-cli#125.
CONTEXT
---
Recently, ecs-cli was migrated to use libcompose for parsing the compose project (including project name and compose yml files). 
Libcompose normalizes the project name by removing '-' and other non alpha-numeric values from the name as seen in the commit https://github.com/docker/libcompose/commit/ca237071578647c6fef35f6d5a9e424bb6deca03, libcompose. This behavior is not documented anywhere in [Docker Compose project_name doc](https://docs.docker.com/compose/reference/envvars/#compose-project-name).
As a result, the project name parsing wasn't backward compatible with ecs-cli. This commit addresses that concern and resets the project name to what the user set (after libcompose parses it).
TEST
---
$ make generate
$ make test
PASS
$ make …
=> Preserve compose project name as user has defined it.

ecs-cli/modules/command/cluster_app.go, ecs-cli/modules/command/cluster_app_test.go
Better validation message when running ecs-cli up without configuring a cluster name. 
https://github.com/aws/amazon-ecs-cli/issues/63
=> Validate cluster name before running Cloudformation Stack

ecs-cli/modules/command/cluster.go, ecs-cli/modules/command/cluster_app.go, ecs-cli/modules/command/cluster_app_test.go, ecs-cli/modules/command/configure_test.go
closes https://github.com/aws/amazon-ecs-cli/issues/44
$ make build
Built ecs-cli
$ make test
PASS
$ ./bin/local/ecs-cli up --keypair *** --capability-iam 
ERRO[0000] Error executing 'up': A CloudFormation stack already exists for the cluster 'cli-demo'. Please specify '--force' to clean up your existing resources. 
$ ./bin/local/ecs-cli up --keypair *** --capability-iam --force
INFO[0000] Created cluster                               cluster=cli-demo
INFO[0001] Waiting for your CloudFormation stack resources to be deleted... 
INFO[0001] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0037] Waiting for your cluster resources to be created... 
INFO[0037] Cloudformation stack status …
=> Cluster up --force tag to delete CloudFormation stack if it exists

ecs-cli/modules/compose/ecs/utils/convert_task_definition.go, ecs-cli/modules/compose/ecs/utils/convert_task_definition_test.go
closes aws/amazon-ecs-cli#156.
Previously, ecs-cli was skipping unresolved environment variables, but looking at the [Compose documentation for variable-substitution](https://docs.docker.com/compose/compose-file/#variable-substitution):
> If an environment variable is not set, Compose substitutes with an empty string
This pull request enforces the same behavior with ecs-cli.
---
$ make build
Built ecs-cli
$ make test
> PASS
$ cat docker-compose.yml 
```yml
version: '2'
services:
test:
image: busybox
environment:
A:
```
$ ./bin/local/ecs-cli compose up
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=test
WARN[0000] Environment variable is unresolved. Setting it to a blank value... …
=> Allow empty environment variable.

ecs-cli/modules/aws/clients/cloudformation/client.go, ecs-cli/modules/aws/clients/ec2/client.go, ecs-cli/modules/aws/clients/ec2/client_test.go, ecs-cli/modules/aws/clients/ecs/client.go, ecs-cli/modules/aws/clients/ecs/client_test.go, ecs-cli/modules/command/cluster_app.go, ecs-cli/modules/command/cluster_app_test.go, ecs-cli/modules/config/aws_config_example.ini, ecs-cli/modules/config/aws_credentials_example.ini, ecs-cli/modules/config/config.go, ecs-cli/modules/config/config_test.go, ecs-cli/modules/config/params.go, ecs-cli/modules/config/params_test.go
- Add support for reading regions from aws profile
- Add support for assume role from aws profile
closes aws/amazon-ecs-cli#53.
closes aws/amazon-ecs-cli#55.
closes aws/amazon-ecs-cli#77.
closes aws/amazon-ecs-cli#92.
----
$ make test
coverage: 76.6% of statements
ok  	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config	5.031s	coverage: 76.6% of statements
-----
Did a compose up: so that the task definition would print the region and account id in the ARN (so we can extract which region and aws account it talked to)
2 AWS profiles:
- default: AccountA (region us-west-2)
- test-cli: AccountA (region eu-west-1)
- another-test-cli: AccountB (region us-east-1)
---
```
$ ./bin/local/ecs-cli configure --cluster uttara
$ ./bin/local/ecs-cli compose up
FATA[0000] Unable to create an instance of …
```
=> Update the order of resolution for aws region and credentials.

ecs-cli/modules/command/cluster_app.go, ecs-cli/modules/command/cluster_app_test.go
Add ability to prompt user when trying to do `ecs-cli down` without `--force` based on feedback for #10
Added testing for new change
=> Fixes #10 to add prompt for deleting cluster

ecs-cli/modules/compose/ecs/utils/convert_task_definition.go, ecs-cli/modules/compose/ecs/utils/convert_task_definition_test.go
Fixes #11 
-Cherry-picked PR #23 (thanks @mcanevet)
-The above PR made it so it wouldn't fail, but the same volume was shared amongst all container paths without a host path, so I added this
-Updated test
-Tested it with `ecs-cli compose up` on random compose file I mushed together:
```
data-container:
image: redis:latest
volumes:
- /tmp/stuff 
- /tmp/bar:/foo/baz
- /tmp/ponies
- /tmp/foo:/tmp/bar
- /tmp/foo:/tmp/baz
mem_limit: 100M
data-container2:
image: redis:latest
volumes:
- /tmp/hi:/tmp/hello
- /tmp/foo:/tmp/foo
- /tmp/unicorns
mem_limit: 100M
```
=> Fixes #11: Error attempting to ecs-cli compose up

ecs-cli/modules/config/readwriter.go, ecs-cli/modules/config/readwriter_test.go
closes https://github.com/aws/amazon-ecs-cli/issues/177
cherry-picked PR https://github.com/aws/amazon-ecs-cli/pull/214, thanks @markriggins
Commands ran: 
`$ make build`
`$ make test`
Testing:
`$ ecs-cli configure --profile *** --cluster ecs-cli-demo`
`$ ecs-cli configure --profile *** --cluster ecs-cli` // set config with shorter cluster name
`$ vim ~/.ecs/config` // verify that the config file is not messed up
=> Truncate the file to avoid messing up the config file

ecs-cli/modules/aws/clients/ecs/client.go, ecs-cli/modules/aws/clients/ecs/mock/client.go, ecs-cli/modules/compose/cli/ecs/app/service_command.go, ecs-cli/modules/compose/ecs/flags.go, ecs-cli/modules/compose/ecs/service.go, ecs-cli/modules/compose/ecs/service_test.go
We want to be able to create a new service and assign it an Application Load Balancer.
Add 5 new params that allows to specify the Load Balancer details in order for the service to be created with an associated ELB/ALB.
Specify the Target Group ARN, Load Balancer Name, Container Name, Container Port and Role to allow the service to register new instances in the ELB/ALB.
* `--target-group-arn`: The full Amazon Resource Name (ARN) of the Elastic Load Balancing target  group associated with a service.
* `--load-balancer-name`: The name of the classic load balancer.
* `--container-name`: The name of the container (as it appears in a container definition) to associate with the load balancer.
* `--container-port`: The port on the container to associate with the load balancer. This port must …
=> AWS ELB-ALB support

ecs-cli/main.go, ecs-cli/modules/aws/clients/ecr/client.go, ecs-cli/modules/aws/clients/ecr/client_test.go, ecs-cli/modules/aws/clients/ecr/mock/client.go, ecs-cli/modules/cli/flags.go, ecs-cli/modules/command/image.go, ecs-cli/modules/command/image_app.go, ecs-cli/modules/command/image_app_test.go
```
$ make build
$ make generate
$ make test
PASS
```
```
$ ./bin/local/ecs-cli images
REPOSITORY NAME     TAG                 IMAGE DIGEST                                                              PUSHED AT           SIZE                
busybox             image               sha256:2efce9f5b0cb8815d192ae634b4c87943d0f0b873d98487ee98f8ed0504bd572   4 weeks ago         703 kB              
busybox             latest              sha256:2efce9f5b0cb8815d192ae634b4c87943d0f0b873d98487ee98f8ed0504bd572   4 weeks ago         703 kB              
busybox             docker-whale        sha256:a7594f1fc305ef3bfb51987f4ac813c9c4faf9bf2116858c8a7b4e3eca7d94b5   4 weeks ago         130 MB              
hello-world         latest …
```
=> List images from ECR

ecs-cli/modules/aws/clients/ecr/client.go, ecs-cli/modules/aws/clients/ecr/client_test.go, ecs-cli/modules/aws/clients/ecr/mock/client.go, ecs-cli/modules/cli/flags.go, ecs-cli/modules/command/image.go, ecs-cli/modules/command/image_app.go, ecs-cli/modules/command/image_app_test.go, ecs-cli/modules/compose/ecs/mocks/project_entity.go, ecs-cli/modules/docker/client.go
```
$ make build
$ make generate
$ make test
PASS
```
```
$ ./bin/local/ecs-cli pull ********.dkr.ecr.us-east-1.amazonaws.com/busybox
INFO[0000] Pulling image                                 repository="**********.dkr.ecr.us-east-1.amazonaws.com/busybox" tag=
INFO[0002] Image pulled                                 
$ ./bin/local/ecs-cli push ***********.dkr.ecr.us-east-1.amazonaws.com/busybox  
INFO[0000] Pushing image                                 repository="******.dkr.ecr.us-east-1.amazonaws.com/busybox" tag=
INFO[0005] Image pushed
$  ./bin/local/ecs-cli push busybox
INFO[0000] Getting AWS account ID...                    
INFO[0000] Tagging image                                 image=busybox repository="********.dkr.ecr.us-east-1.amazonaws.com/busybox" tag=
INFO[0000] Image tagged …
```
=> Allow ECR push/pull with URI

ecs-cli/modules/compose/ecs/project_test.go, ecs-cli/modules/compose/ecs/utils/convert_task_definition.go, ecs-cli/modules/compose/ecs/utils/convert_task_definition_test.go
closes aws/amazon-ecs-cli#145
Adding the ability to specify `mem_reservation` in a docker-compose file, as per the [aws spec](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html), since it is now supported by [libcompse](https://github.com/docker/libcompose/pull/431/files)
=> passing memory reservation to ecs via compose

ecs-cli/modules/aws/clients/ec2/client.go, ecs-cli/modules/aws/clients/ec2/client_test.go, ecs-cli/modules/aws/clients/ecs/client.go, ecs-cli/modules/aws/clients/ecs/client_test.go, ecs-cli/modules/compose/ecs/entity.go, ecs-cli/modules/compose/ecs/entity_test.go
closes aws/amazon-ecs-cli#231.
`ecs-cli ps` gives segmentation violation error because it is trying to get the `PublicIPAddress` using the `EC2InstanceID` provided by the container instance, but the EC2 instance no longer exist.
This can be reproduced by first **stop** then **terminate** the EC2 instance. This error should go away without the fix ECS container instance recognize that the EC2 instance has been terminated.
=> Fix segmentation violation error when ec2InstanceId does not exist

ecs-cli/modules/aws/clients/ecs/client.go, ecs-cli/modules/aws/clients/ecs/mock/client.go, ecs-cli/modules/compose/cli/ecs/app/app.go, ecs-cli/modules/compose/cli/ecs/app/app_test.go, ecs-cli/modules/compose/cli/ecs/app/command.go, ecs-cli/modules/compose/ecs/entity.go, ecs-cli/modules/compose/ecs/mocks/project.go, ecs-cli/modules/compose/ecs/mocks/project_entity.go, ecs-cli/modules/compose/ecs/project.go, ecs-cli/modules/compose/ecs/service.go, ecs-cli/modules/compose/ecs/service_test.go, ecs-cli/modules/compose/ecs/task.go
Addresses Issue #148
reference #229
`compose run` supports multi-argument commands as:
`<container1> “<cmd0> <cmd1> <cmd2>” <container2> “<cmd0> <cmd1> <cmd2>...”`
=> Proposal: compose run supports  quoted multi-argument commands

Makefile, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go
Using a marshalled json representation for the task definition data to be deterministic hash
Unit test to provide coverage of SortedGoString (the bugfix is fixing a non-deterministic irreproducible scenario)
=> Deterministic TaskDefinitionCacheHash for the local cache

ecs-cli/modules/cli/compose/entity/entity_helper.go, ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/flags.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go
This addresses #188 by providing a `--task-role-arn` flag with the compose command. The TaskRoleArn is passed to the RegisterTaskDefinition API call. Storing it as an property in the yml file is not an option since it would require modifying libCompose, so I opted for the command line argument instead.
Let me know if you'd like me to make any adjustments before merging.
=> Adds support for --task-role-arn with compose commands

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/cli/compose/factory/factory_test.go, ecs-cli/modules/cli/image/image_app_test.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/commands/cluster/cluster_command.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/configure/configure_command.go, ecs-cli/modules/commands/flags.go, ecs-cli/modules/commands/image/image_command.go, ecs-cli/modules/config/config.go, ecs-cli/modules/config/params.go, ecs-cli/modules/config/params_test.go
Closes https://github.com/aws/amazon-ecs-cli/issues/174, #71
Order of region/cluster resolution:
1) inline flag
2) environment variable
3) ECS config
=> Inline region and cluster flags for all commands

README.md, ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/clients/aws/cloudformation/params.go, ecs-cli/modules/clients/aws/cloudformation/template.go
closes #113 
The --security-group command now supports multiple security groups specified as a comma separated list. A single security group can still be specified as before.
=> Support Multiple Security Groups in the Up Command

ecs-cli/Godeps/Godeps.json, ecs-cli/modules/cli/compose/factory/factory.go, ecs-cli/modules/cli/compose/factory/factory_test.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/vendor/github.com/docker/libcompose/cli/app/app.go, ecs-cli/vendor/github.com/docker/libcompose/cli/app/events.go, ecs-cli/vendor/github.com/docker/libcompose/cli/app/types.go, ecs-cli/vendor/github.com/docker/libcompose/cli/app/version.go, ecs-cli/vendor/github.com/docker/libcompose/cli/command/command.go, ecs-cli/vendor/github.com/docker/libcompose/version/version.go
closes #57 #215 
- The `--file` flag can be used to specify multiple compose files
- Both `docker-compose.yml` and `docker-compose.override.yml` will be read if they exist and the `--file` flag is not used
- This mimics the behavior of docker-compose as described [here](https://docs.docker.com/compose/extends/#multiple-compose-files)
```sh
$ make test
env -i PATH=$PATH GOPATH=$GOPATH GOROOT=$GOROOT go test -timeout=120s -v -cover ./ecs-cli/modules/...
```
- Tests Volumes, Links, CPU, Memory
(each folder represents a test case)
[Test Docker files.zip](https://github.com/aws/amazon-ecs-cli/files/1090771/Test.Docker.files.zip)
[test6.zip](https://github.com/aws/amazon-ecs-cli/files/1106325/test6.zip)
=> Support multiple compose files with --file (or -f), and docker-compose.override.yml

ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/config/params.go
closes #270
Examples:
```sh
$ ecs-cli compose --cluster other --region us-east-2 up
$ ecs-cli compose up --cluster other --region us-east-2
```
Both will produce the desired behavior (cluster and region in the config is overridden) and both produce the same behavior.
```sh
$ make test
```
```sh
$ ecs-cli compose create --cluster other --region us-east-2
$ ecs-cli compose start --cluster other --region us-east-2
$ ecs-cli compose up --cluster other --region us-east-2
$ ecs-cli compose ps --cluster other --region us-east-2
$ ecs-cli compose scale 2 --cluster other --region us-east-2
$ ecs-cli compose run --cluster other --region us-east-2
$ ecs-cli compose stop --cluster other --region us-east-2
$ ecs-cli compose down --cluster other --region us-east-2
```
```sh
$ ecs-cli compose --cluster …
```
=> Cluster and Region flags allowed both before and after the subcommand for compose commands. 

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/clients/aws/cloudformation/params.go, ecs-cli/modules/clients/aws/cloudformation/template.go, ecs-cli/modules/commands/cluster/cluster_command.go, ecs-cli/modules/commands/flags.go
This allows the customer to specify the name of a custom IAM Role as the instance role for
their EC2 Instance Profile. NOTE: If the correct IAM Policy
(`AmazonEC2ContainerServiceforEC2Role`) is not attached to the custom instance
role, the create cluster command will succeed but no instances will be
launched.
If a custom role is specified, the `capability-iam` flag is not needed.
Closes #19.
```sh
$ make test
```
```sh
$ ecs-cli up --keypair my-keypair --size 2 --cluster my-test-cluster --instance-role ecsInstanceRole
```
```sh
$ ecs-cli up --keypair my-keypair --size 2 --cluster my-test-cluster --instance-role foo --capability-iam
=> ERRO[0000] Error executing 'up': Cannot specify custom role when '--capability-iam' flag is set
$ ecs-cli up --keypair my-keypair --size 2 --cluster …
```
=> Add `--instance-role` flag to cluster up command

ecs-cli/modules/cli/compose/entity/service/service_helper.go, ecs-cli/modules/cli/compose/entity/task/task_helper.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/flags.go, ecs-cli/modules/utils/waiters/waiters.go
- Added a configurable timeout
`ecs-cli compose service up --timeout 5`
- If the running count of tasks is still not at the desired count and has not changed for timeout minutes, then the CLI times out. 
- timeout defaults to 5 minutes
- This addresses the problems with the current behavior which cause large deployments to timeout even though progress in starting tasks is being made and the update will eventually succeed.
- Improved error/info messages
- the service event logs are now printed 
- new events are printed only (note that ECS may not always emit events)
Addresses #286
closes #269 
Help Text:
--timeout value                         [Optional] Specifies the floating point value timeout in minutes to wait for the running task count to change. If the running task count has not …
=> Improved user experience in the compose service up command

ecs-cli/modules/clients/aws/cloudformation/template.go
Introduced a bug in `c07bc184`:
```
$ ecs-cli up --capability-iam --keypair hhh-2 --size 1 --cluster test
INFO[0000] Created cluster                               cluster=test region=us-west-2
INFO[0000] Waiting for your cluster resources to be created... 
INFO[0001] Cloudformation stack status                   stackStatus="CREATE_IN_PROGRESS"
ERRO[0061] Failure event                                 reason="Value of property Roles must be of type List of String" resourceType="AWS::IAM::InstanceProfile"
```
This change fixes this error and maintains original functionality of the clusterUp command with default IAM Instance Role.
```
$ ecs-cli up --capability-iam --keypair hhh-2 --size 1 --cluster test
INFO[0000] Created cluster                               cluster=test region=us-west-2 …
```
=> Bugfix: Typo in Roles field in IAM Instance Profile

README.md, scripts/publish-functions.sh, scripts/publish-staged
- Updated scripts so that they can push to buckets across partitions (cn-north-1)
- One account is used to pull from the staging S3 bucket (alpha), and then another account is used for the push to the public S3 bucket- this is necessary because copying across partitions is not supported (the China regions are separated from the rest of AWS and require separate accounts).
Testing done:
```
$ ./scripts/publish-staged -d false -p cli -o cli-bjs -s ec2-madison-alpha-cli
Publishing as ecs-cli-linux-amd64-v0.6.2
RUNNING: s3_cp s3://ec2-madison-alpha-cli/ecs-cli-linux-amd64-v0.6.2 s3://amazon-ecs-cli/ecs-cli-linux-amd64-v0.6.2
Copying s3://ec2-madison-alpha-cli/ecs-cli-linux-amd64-v0.6.2 to s3://amazon-ecs-cli/ecs-cli-linux-amd64-v0.6.2
download: …
```
=> Modifications to publishing scripts to support China Regions

Makefile
What it says on the tin: using `go install` causes `make generate-deps` to fail.
=> Go get instead of install to retrieve code

ecs-cli/main.go, ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/compose/compose_app.go, ecs-cli/modules/cli/configure/configure.go, ecs-cli/modules/cli/image/image_app.go, ecs-cli/modules/commands/cluster/cluster_command.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/configure/configure_command.go, ecs-cli/modules/commands/flags.go, ecs-cli/modules/commands/image/image_command.go, ecs-cli/modules/commands/license/license_command.go
closes #306 
(These changes were already reviews as part of #302; pulling them out into a separate PR so that this can be pushed sooner.)
- CLI now consistently returns a non-zero exit code if there is an error condition 
- All commands now use `logrus.fatal` for error logging (previously it was a random mix of `logrus.error` and `logrus.fatal`. This change is necessary to make the simple integration tests work. 
- Usage errors (incorrect flags, incorrect commands, etc) now set the exit code to be non-zero.
Examples:
```sh
$ ecs-cli configure cat
FATA[0000] Error initializing: Missing required argument 'cluster' 
$ echo $?
1
```
```sh
$ ecs-cli up --cat
ERRO[0000] flag provided but not defined: -cat   
.... <help text>... 
$ echo $?
1
```
```sh
$ ecs-cli compose up
ERRO[0000] Failed to …
```
=> Consistently return a non zero exit status for error conditions.

ecs-cli/modules/commands/compose/service/compose_service_command.go
closes #325 
Compose Service Up:
- If the service does not exist, then it Creates the service, and calls Start to set the desired count to 1.
- If the service exist and has a desired count of 0, then Start is called to update it to 1.
- If a non-zero running count already exists, then it is unchanged. Update service called to update the service with a new version of the task definition. 
```
$ ecs-cli compose service up --help
NAME:
ecs-cli compose service up - Creates a new ECS service or updates an existing one according to your compose file. For new services or existing services with a current desired count of 0, the desired count for the service is set to 1. For existing services with non-zero desired counts, a new task definition is created to reflect any changes to the compose file …
```
=> Update compose service up and compose service start help text.

ecs-cli/modules/cli/compose/entity/entity_helper.go, ecs-cli/modules/cli/compose/entity/entity_test.go
closes #310 
- Displays private IP if the instance doesn't have a public IP
Public IP (same as old functionality)
```
$ ecs-cli ps --cluster PublicIP                                       
Name                                            State    Ports                   TaskDefinition
f3b7b93d-af17-4cf0-b6b9-c7bf2c4b61b2/wordpress  RUNNING  13.59.2.148:80->80/tcp  ecscompose-test2:15
f3b7b93d-af17-4cf0-b6b9-c7bf2c4b61b2/mysql      RUNNING                          ecscompose-test2:15
```
Private IP
```
$ ecs-cli ps --cluster PrivateIP
Name                                            State    Ports                  TaskDefinition
3b06a88c-7c6b-4eb9-8c40-287fcad2a19e/wordpress  RUNNING  10.0.1.121:80->80/tcp  ecscompose-test2:15
3b06a88c-7c6b-4eb9-8c40-287fcad2a19e/mysql      RUNNING …
```
=> PS command displays private IPs

ecs-cli/Godeps/Godeps.json, ecs-cli/modules/cli/license/license.go, ecs-cli/modules/clients/aws/ec2/mock/sdk/ec2iface_mock.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/version.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, ecs-cli/vendor/github.com/golang/mock/AUTHORS, ecs-cli/vendor/github.com/golang/mock/CONTRIBUTORS, ecs-cli/vendor/github.com/pkg/errors/.gitignore, ecs-cli/vendor/github.com/pkg/errors/.travis.yml
[On Friday, ECS added support for adding and dropping linux capabilities](https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-ecs-adds-support-for-adding-or-dropping-linux-capabilities-to-containers/)
- added support for cap_add and cap_drop using the docker compose fields
- updated aws-sdk-go to the latest release
Testing Done
- Ran `ecs-cli compose up` with this docker compose file:
```
version: '2'
services:
mysql:
image: mysql
cpu_shares: 100
mem_limit: 524288000
environment:
MYSQL_ROOT_PASSWORD: password1234catscatscatsdogsdogspudding
cap_add:
- ALL
cap_drop:
- NET_ADMIN
- SYS_ADMIN
```
Which resulted in the following Container Definition:
```
{
"linuxParameters": {
"capabilities": {
"add": [
"ALL"
],
"drop": [
"NET_ADMIN",
"SYS_ADMIN"
]
}
},
```
=> Add support for cap_add and cap_drop

README.md, ecs-cli/modules/cli/compose/entity/entity_helper.go, ecs-cli/modules/cli/compose/factory/factory.go, ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/flags.go, ecs-cli/modules/config/params.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go
Closes #153 and #188.
Addresses most of #267.
Testing:
Compose file data:
```
~/sandbox/test_fields$ cat docker-compose.yml 
version: '2'
services:
wordpress:
image: wordpress
cpu_shares: 100
mem_limit: 52428800
ports:
- "80:80"
mysql:
image: mysql
cpu_shares: 100
mem_limit: 524288000
environment:
MYSQL_ROOT_PASSWORD: foobar
```
**NOTE**: cannot include "links" field in service definition if network mode is "host" (See: [network_mode in docker-compose](https://docs.docker.com/compose/compose-file/#network_mode))
ECS params data:
```
$ cat ecs-params.yml
version: 1
ecs_network_mode: host 
```
Calling `compose service up`:
```
~ ecs-cli compose --file docker-compose.yml --ecs-params ecs-params.yml service up --cluster test-ecs-fields
INFO[0000] Using ECS task definition …
```
=> Support ECS fields in compose commands

ecs-cli/modules/clients/aws/cloudformation/template.go
Previously, the MinSize specified in the AutoScaling Group for a cluster
was 1 instance. This meant that customers would not be able to use the
ecs-cli scale command to scale their cluster down to 0. This change
fixes that issue.
Resolves #335
=> [BUGFIX] Change default cluster MinSize to 0

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/cli/compose/entity/entity_helper.go, ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/cli/configure/configure.go, ecs-cli/modules/cli/configure/configure_test.go, ecs-cli/modules/cli/configure/migrate.go, ecs-cli/modules/commands/configure/configure_command.go, ecs-cli/modules/commands/flags.go, ecs-cli/modules/config/config_v1.go, ecs-cli/modules/config/destination.go, ecs-cli/modules/config/destination_test.go, ecs-cli/modules/config/params.go, ecs-cli/modules/config/params_test.go, ecs-cli/modules/config/readwriter.go, ecs-cli/modules/config/readwriter_v1.go, ecs-cli/modules/config/readwriter_v1_test.go, ecs-cli/modules/utils/compose/name.go
Implements #252
- New Migrate command allows users to migrate their config from the old format to the new format
- Removed the prefixes from the config according to proposal #252 
- Added unit test for Migrate command; all relevant pre-existing tests were modified for the removal of the prefixes.
=> Removed prefixes from the configs. Implemented migrate command.

ecs-cli/modules/cli/configure/configure.go, ecs-cli/modules/config/config_v1.go, ecs-cli/modules/config/params.go, ecs-cli/modules/config/readwriter.go, ecs-cli/modules/config/readwriter_v1_test.go
Prefix removal caused a bug in the case where the old ini style config is being read. If a flag is used to override the cluster name, then the CFN Stack Name will not be appropriately set based upon the value in the flag.
=> Fixed bug with CFNStackName.

ecs-cli/modules/commands/flags.go, ecs-cli/modules/config/params.go, ecs-cli/modules/config/params_test.go
The old CLI allowed the storing of a name of an AWS Profile in the configuration file. That functionality has been removed, instead, a new flag `--aws-profile` has been added to all commands that allows the name of an AWS Profile to be specified inline.
=> Add aws-profile flag

README.md, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go
=> Add ability to set "essential" field on containers

ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/configure/configure_command.go
Adds on usage error for:
- new configure commands
- old compose service commands which I forgot to add it to before
For a reminder of what this does, see this example:
```
$ ecs-cli configure profile default --cat
ERRO[0000] flag provided but not defined: -cat          
NAME:
ecs-cli configure profile default - Sets the default profile.
USAGE:
ecs-cli configure profile default [command options] [arguments...]
OPTIONS:
--profile-name value  Specifies the name of the profile to use by default.
$ echo $?
1
```
Before OnUsageError was specified, the CLI would not set the unix exit code to be 1 (it would be 0, which is wrong).
=> Add usage error for all commands

ecs-cli/modules/cli/configure/configure.go, ecs-cli/modules/cli/configure/configure_test.go, ecs-cli/modules/cli/configure/migrate.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/config/config_v1.go, ecs-cli/modules/config/params.go, ecs-cli/modules/config/params_test.go, ecs-cli/modules/config/readwriter.go, ecs-cli/modules/config/readwriter_v1.go, ecs-cli/modules/config/readwriter_v1_test.go
- Bug Fix: Re-added the --timeout flag to compose service commands which had accidentally been removed. 
- Bug Fix: Use of a pointer in the migrate warning function caused the new credential file to be written with a scrambled key pair.
- Enhancement: Improve migrate warning text.
- Bug Fix: V1 ReadWriter now sets unused fields to be empty strings (ComposeProjectNamePrefix and CFNStacknamePrefix). This fixes a bug where the old iniReader was setting all fields to be default.
Bug Fix: Corrected logic for setting CFNStackName.
=> Bug fixes and enhancements to multiple configurations changes

ecs-cli/modules/config/readwriter_v1.go
```
$ ecs-cli ps --ecs-profile asdfasdf
FATA[0000] Error executing 'ps Error loading config: ECS Profile asdfasdf could not be found. Configure profiles using 'ecs-cli configure profile'. 
```
(Previously this failed without an error message specifying that the profile could not be found.)
=> Print Error message if ecs-profile or cluster-config is not found

Makefile, README.md, ecs-cli/modules/config/destination.go, ecs-cli/modules/config/destination_test.go, ecs-cli/modules/utils/cache/fs_cache.go, ecs-cli/modules/utils/cache/fs_cache_test.go, scripts/publish-staged, scripts/stage.sh
Changes:
- `make windows-build` creates `ecs-cli` in `/bin/windows-amd64`
- `make docker-build` also now creates the windows binary as well. 
- The ECS CLI config directory is set as `%userprofile%\AppData\local\ecs` (`C:\\Users\<User>\AppData\local\ecs`) on Windows.
=> Add support for building on Windows

ecs-cli/main.go, ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/clients/aws/cloudformation/params.go, ecs-cli/modules/clients/aws/cloudformation/params_test.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/commands/flags.go, ecs-cli/modules/version/gen/version-gen.go
Fixed issues identified by running [github.com/GoASTScanner/gas](https://github.com/GoASTScanner/gas). 
Below are the results from running the scanning tool; I fixed a subset of the issues that were important. (Several of the warnings were for ignoring returned errors for standard library functions that are used to print to stdout; I ignored these warnings.)
[gas_results.txt](https://github.com/aws/amazon-ecs-cli/files/1436122/gas_results.txt)
=> Fixed issues identified by running GoASTScanner

ecs-cli/modules/config/destination_test.go
- Merging caused the name of the function `NewDefaultDestination()` to be failed to be updated in the test files.
=> [Bugfix] Fixed conflict caused by merging Windows support.

ecs-cli/modules/app.go, ecs-cli/modules/app_test.go, ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/cli/compose/context/context.go, ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_helper.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/cli/compose/factory/factory_test.go, ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/cli/compose/project/project_test.go, ecs-cli/modules/cli/configure/configure.go, ecs-cli/modules/cli/configure/configure_test.go, ecs-cli/modules/cli/image/image_app.go, ecs-cli/modules/commands/cluster/cluster_command.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/configure/configure_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/image/image_command.go, ecs-cli/modules/commands/license/license_command.go, ecs-cli/modules/config/config_test.go, ecs-cli/modules/config/config_v1.go, ecs-cli/modules/config/params.go, ecs-cli/modules/config/params_test.go, ecs-cli/modules/config/readwriter.go, ecs-cli/modules/config/readwriter_v1_test.go
This fixes the inconsistent naming of the "command" package.
=> Move flags.go into own package

README.md
Partially addresses questions in #372, #369, #284
- New configure information
- Windows Binaries with specific version tags
=> README Changes for v1.0.0

ecs-cli/modules/config/config_test.go, ecs-cli/modules/config/config_v1.go
=> [Bugfix] Assume role works regardless of how AWS Profile is specified

.travis.yml
Versions older than 1.7.4 are not supported on MacOS Sierra and return a
fatal error MSpanList_Insert https://github.com/golang/go/issues/17492.
Fixes #384
=> Remove go 1.6 from travis build

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/clients/aws/cloudformation/client.go, ecs-cli/modules/clients/aws/cloudformation/mock/client.go, ecs-cli/modules/clients/aws/cloudformation/params.go, ecs-cli/modules/clients/aws/cloudformation/params_test.go
* Bugfix - `ecs-cli scale` now works with old versions of the CFN template. Fixes #330 
* Enhancement - `ecs-cli scale` can scale any cluster created by the ECS Console 
Testing done:
```
$ ecs-cli configure --cluster OLD --region ca-central-1 --cfn-stack-name amazon-ecs-cli-setup-OLD
$ ecs-cli scale --size 4 --capability-iam
INFO[0001] Waiting for your cluster resources to be updated... 
INFO[0001] Cloudformation stack status                   stackStatus="UPDATE_IN_PROGRESS"
$ ecs-cli configure --cluster LinuxConsole --region ca-central-1 --cfn-stack-name EC2ContainerService-LinuxConsole
INFO[0000] Saved ECS CLI cluster configuration default. 
$ ecs-cli scale --size 2 --capability-iam
INFO[0001] Waiting for your cluster resources to be updated... 
INFO[0001] Cloudformation stack status …
```
=> Make ecs-cli scale compatible with CFN templates created by the ECS Console and past versions of the ECS CLI

ecs-cli/modules/config/ami/ami.go
Tested new AMIs in all regions with "ecs-cli up". Example:
... % ./ecs-cli up --cluster ami-test --region us-east-1 --capability-iam
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair. 
INFO[0000] Created cluster                               cluster=ami-test region=us-east-1
INFO[0001] Waiting for your cluster resources to be created... 
INFO[0001] Cloudformation stack status                   stackStatus="CREATE_IN_PROGRESS"
INFO[0062] Cloudformation stack status                   stackStatus="CREATE_IN_PROGRESS"
INFO[0123] Cloudformation stack status                   stackStatus="CREATE_IN_PROGRESS"
Cluster creation succeeded.
VPC created: vpc-1b1b3063
Security Group created: sg-f0d07384
Subnet created: subnet-0a7df557
Subnet created: subnet-43eea427
=> AMI update

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/mock/client.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/flags/flags.go
...with target group
```
.\bin\local\ecs-cli.exe compose --file .\httpd-new.yml --project-name httpd-new-test service create --target-group-arn arn:aws:elasticloadbalancing:ap-northeast-1:[...]:targetgroup/cli-tg-2/79a1e2ac87091435 --container-name httpd-new --container-port 80 --health-check-grace-period 25
time="2018-01-08T16:09:25-08:00" level=warning msg="Skipping unsupported YAML option..." option name=networks
time="2018-01-08T16:09:25-08:00" level=warning msg="Skipping unsupported YAML option for service..." option name=networks service name=httpd-new
time="2018-01-08T16:09:26-08:00" level=info msg="Using ECS task definition" TaskDefinition="httpd-new-test:4"
time="2018-01-08T16:09:27-08:00" level=info msg="Created an ECS service" health-check-grace-period=25 service=httpd-new-test …
```
=> Add HealthCheckGracePeriod to compose service create and up

ecs-cli/modules/commands/cluster/cluster_command.go
```
~/go/src/github.com/aws/amazon-ecs-cli(dev)$ ecs-cli down --help
NAME:
ecs-cli down - Deletes the CloudFormation stack that was created by ecs-cli up and the associated resources.
USAGE:
ecs-cli down [command options] [arguments...]
OPTIONS:
--force, -f                [Optional] Acknowledges that this command permanently deletes resources.
--region value, -r value   [Optional] Specifies the AWS region to use. Defaults to the region configured using the configure command
--cluster-config value     [Optional] Specifies the name of the ECS cluster configuration to use. Defaults to the default cluster configuration.
--ecs-profile value        [Optional] Specifies the name of the ECS profile configuration to use. Defaults to the default profile configuration. [$ECS_PROFILE]
--aws-profile …
```
=> Update documentation on force flag for cluster down

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/mock/client.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/flags/flags.go
"compose service start" with --force-deployment on already running service
```
$>  .\bin\local\ecs-cli.exe compose --file .\httpd-new.yml --project-name httpd-new-test service start --force-deployment
time="2018-01-22T16:51:39-08:00" level=warning msg="Skipping unsupported YAML option..." option name=networks
time="2018-01-22T16:51:39-08:00" level=warning msg="Skipping unsupported YAML option for service..." option name=networks service name=httpd-new
time="2018-01-22T16:51:40-08:00" level=info msg="Forcing new deployment of running ECS Service" desiredCount=1 force-deployment=true serviceName=httpd-new-test
time="2018-01-22T16:51:40-08:00" level=info msg="Updated ECS service successfully" desiredCount=1 force-deployment=true serviceName=httpd-new-test
time="2018-01-22T16:51:40-08:00" …
```
=> Add force-deployment flag to compose service start and up

ecs-cli/modules/cli/configure/configure.go, ecs-cli/modules/cli/configure/configure_test.go, ecs-cli/modules/commands/configure/configure_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/config/config_test.go, ecs-cli/modules/config/config_v1.go, ecs-cli/modules/config/readwriter_v1.go, ecs-cli/modules/config/readwriter_v1_test.go
- Closes #409 
Usage:
```
$ ecs-cli configure profile --access-key ACCESS --secret-key SECRET --session-token TOKEN
INFO[0000] Saved ECS CLI profile configuration default. 
$ cat credentials 
version: v1
default: default
ecs_profiles:
default:
aws_access_key_id: ACCESS
aws_secret_access_key: SECRET
aws_session_token: TOKEN
```
Without session token:
```
$ ecs-cli configure profile --access-key ACCESS --secret-key SECRET
INFO[0000] Saved ECS CLI profile configuration default. 
$ cat credentials 
version: v1
default: default
ecs_profiles:
default:
aws_access_key_id: ACCESS
aws_secret_access_key: SECRET
```
=> Support aws_session_token in ECS Profiles

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go
Removed UpdateServiceCount() client method and simplified Up() unit tests. 
```
$> .\bin\local\ecs-cli.exe compose --file ...\httpd-new.yml --project-name httpd-new-test --ecs-params ...\ecs-params.yml service up --deployment-max-percent 251 --deployment-min-healthy-percent 53
time="2018-01-31T15:25:19-08:00" level=info msg="Using ECS task definition" TaskDefinition="httpd-new-test:7"
time="2018-01-31T15:25:20-08:00" level=info msg="Updated ECS service successfully" deployment-max-percent=251 deployment-min-healthy-percent=53 desiredCount=1 serviceName=httpd-new-test
time="2018-01-31T15:25:20-08:00" level=info msg="Service status" desiredCount=1 runningCount=1 serviceName=httpd-new-test
time="2018-01-31T15:25:20-08:00" level=info msg="ECS Service has reached a stable state" desiredCount=1 …
```
=> Remove UpdateServiceCount() method from service, client

ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/mock/client.go
Client refactor & mock regen for https://github.com/aws/amazon-ecs-cli/pull/422
```
...
=== RUN   TestGetIdFromArn
--- PASS: TestGetIdFromArn (0.00s)
PASS
coverage: 85.6% of statements
ok  	github.com/aws/amazon-ecs-cli/ecs-cli/modules/utils/compose	0.012s	coverage: 85.6% of statements
?   	github.com/aws/amazon-ecs-cli/ecs-cli/modules/utils/logger	[no test files]
?   	github.com/aws/amazon-ecs-cli/ecs-cli/modules/utils/waiters	[no test files]
?   	github.com/aws/amazon-ecs-cli/ecs-cli/modules/version	[no test files]
?   	github.com/aws/amazon-ecs-cli/ecs-cli/modules/version/gen	[no test files]
```
=> Remove UpdateServiceCount from ecs client, regen mocks

.travis.yml, ecs-cli/modules/cli/compose/container/container_test.go, ecs-cli/modules/cli/compose/project/project_test.go, ecs-cli/modules/cli/license/license_test.go, ecs-cli/modules/config/config.go, ecs-cli/modules/config/readwriter.go, ecs-cli/modules/config/readwriter_v1.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go
Fixes #441 
Tests were failing for two reasons:
1. Incorrect verbs in `Errorf` and `Fatalf` (`go test` is a bit more strict about that now)
2. A change in behavior around reflection: Prior to Go 1.10, a reflection bug allowed embedded pointers to unexported struct types to be incorrectly accessible.  Go 1.10 fixed this bug, which broke the CLI's ability to set values in the unexported iniSectionKeys struct pointer embedded in the iniCLIConfig struct.  See https://golang.org/doc/go1.10#reflect.
I also added Travis support for Go 1.9 and 1.10 so we actually test with those versions too.
=> Make `make test` pass with Go 1.10

.gitignore, ecs-cli/modules/cli/cluster/cluster_app.go
The CLI help indicates the cluster and region flags are optional.
However, this is only true if defaults are stored in .ecs/*
This commit checks for the presence of the 'cluster' flag, and
throws an error if not set. This way, we won't call the ECS API
and we present a clearer failure message.
```
➜  ecs-cli scale --capability-iam --size 0
FATA[0000] Error executing 'scale': InvalidParameterException: Clusters can not be blank.
status code: 400, request id: b636f430-2ef5-11e8-bfed-5775413ad506
➜  ecs-cli ps
FATA[0000] Error executing 'ps InvalidParameterException: Clusters can not be blank.
status code: 400, request id: 8e9625e2-2ef5-11e8-be00-2f76bba63d2b
```
```
➜  ecs-cli scale --capability-iam --size 0
FATA[0000] Error executing 'scale': Please configure a cluster using the configure …
```
=> Fail with an informative error message if cluster isn't set

ecs-cli/modules/cli/image/image_app.go, ecs-cli/modules/cli/image/image_app_test.go
- Fixes bug #361. This simply required correcting the regex.
=> Support forward slash in image names

ecs-cli/modules/cli/compose/containerconfig/containerconfig.go, ecs-cli/modules/utils/compose/convert_task_definition.go
These correspond to docker compose fields currently supported in V1/V2
=> Add more fields to ContainerConfig

ecs-cli/modules/cli/compose/project/project_test.go
The task def converter validates that both path and size are present for
tmpfs values. This is to make the test more accurate to actual expected
input.
=> Update tmpfs field in project test

ecs-cli/main.go
Fixes #490 
Previously, I tried to fix this in https://github.com/aws/amazon-ecs-cli/pull/314  and https://github.com/aws/amazon-ecs-cli/pull/343. But that solution missed a few cases.
(The following cases were missed by the previous PRs)
```
$ ecs-cli --cat
Incorrect Usage. flag provided but not defined: -cat
NAME:
ecs-cli - Command line interface for Amazon ECS
USAGE:
ecs-cli [global options] command [command options] [arguments...]
VERSION:
1.5.0 (*f650427)
AUTHOR:
Amazon Web Services
COMMANDS:
configure  Stores a single cluster configuration.
up         Creates the ECS cluster (if it does not already exist) and the AWS resources required to set up the cluster.
down       Deletes the CloudFormation stack that was created by ecs-cli up and the associated resources.
scale      Modifies …
```
=> Consistently set exit code to 1 for all CLI usage errors

ecs-cli/modules/cli/compose/project/project_parseV3.go, ecs-cli/modules/cli/compose/project/project_parseV3_test.go
`project` pkg test output:
```
PS C:\~\GO\src\github.com\aws\amazon-ecs-cli> go test -timeout=120s -v -cover ./ecs-cli/modules/cli/compose/project
=== RUN   TestParseV1V2_Version1_HappyPath
time="2018-05-16T13:50:19-07:00" level=warning msg="Ignoring the ip address while transforming it to task definition" container=web portMapping="127.0.0.1:8001:8001"
--- PASS: TestParseV1V2_Version1_HappyPath (0.01s)
=== RUN   TestParseV1V2_Version2Files
--- PASS: TestParseV1V2_Version2Files (0.00s)
=== RUN   TestParseV1V2_Version1_WithEnvFile
--- PASS: TestParseV1V2_Version1_WithEnvFile (0.00s)
=== RUN   TestParseV3WithOneFile
--- PASS: TestParseV3WithOneFile (0.01s)
=== RUN   TestParseV3WithMultipleFiles
--- PASS: TestParseV3WithMultipleFiles (0.01s)
=== RUN   TestThrowErrorOnBadYaml
--- PASS: …
```
=> Convert v3 env vars to containerConfig Environment

ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/ecs_params_reader_test.go
compose output with new ECS service params logged out (error on creating task def expected ATM):
```
$> ..\..\Documents\GO\src\github.com\aws\amazon-ecs-cli\bin\local\ecs-cli.exe compose create
INFO[0000] ECS content: &{Version:1 TaskDefinition:{NetworkMode:bridge TaskRoleArn: ContainerDefinitions:map[web:{Essential:false CPUShares:2 Memory:10 MemoryReservation:8}] ExecutionRole: TaskSize:{Cpu: Memory:}} RunParams:{NetworkConfiguration:{AwsVpcConfiguration:{Subnets:[] SecurityGroups:[] AssignPublicIp:}}}}
ERRO[0000] Unable to open ECS Compose Project            error="cannot create a task definition with no containers; invalid service config"
FATA[0000] Unable to create and read ECS Compose Project  error="cannot create a task definition with no containers; invalid service config"
``` …
=> Add service cpu, memory, and memory_reservation fields to ecs-params

ecs-cli/modules/clients/aws/cloudformation/client.go
Test output:
```
$> ~\GO\src\github.com\aws\amazon-ecs-cli\bin\local\ecs-cli.exe down --force --cluster-config test
INFO[0001] Waiting for your cluster resources to be deleted...
INFO[0001] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0063] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0124] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0186] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0248] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0309] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0371] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS …
```
=> Fix stack timeout message to work for creation and deletion

ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/compose/ecs_params_reader.go
Previously, the only field on a service in ecs-params.yml was essential.
The desired behavior is that if essential is not specified, the default
is true. However, the yaml unmarshaller by default sets any unspecified
field in the yaml to the zero value, which in the case of a boolean is
false. Since we did not expect customers to specify the 'services' field
at all in the past unless they wished to specify essential to be false,
this worked. However, with the addition of other fields (CPU, Memory) on
container definitions, we need to ensure that the default for essential
is still true even when not specified.
=> Set default for essential to be true on ContainerDef

ecs-cli/modules/cli/compose/adapter/convert_test.go, ecs-cli/modules/cli/compose/project/mock/project.go, ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/cli/compose/project/project_parseV1V2.go, ecs-cli/modules/cli/compose/project/project_parseV1V2_test.go, ecs-cli/modules/cli/compose/project/project_test.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go
Also changed tests for ConvertToMountPoints to better reflect actual
inputs for volumes in docker-compose, as well as to account for mutating
top-level volumes struct
TODO: set volumes on project in parseV3
=> Add top-level volumes to ecsProject

ecs-cli/modules/cli/compose/adapter/convert.go, ecs-cli/modules/cli/compose/adapter/convert_test.go, ecs-cli/modules/cli/compose/project/project_parseV1V2.go, ecs-cli/modules/cli/compose/project/project_parseV3.go, ecs-cli/modules/cli/compose/project/project_parseV3_test.go
`make` and `make test` pass
docker-compose file:
```
version: '3'
services:
wordpress:
image: wordpress
ports:
- "80:80"
links:
- mysql
logging:
driver: awslogs
options: 
awslogs-group: multiservice-wordpress
awslogs-region: us-east-1
awslogs-stream-prefix: wordpress
mysql:
image: mysql
environment:
MYSQL_USER: test-user
volumes:
- /opt/data:/var/lib/mysql
- test:/stuff/test:ro
logging:
driver: awslogs
options: 
awslogs-group: multiservice-mysql
awslogs-region: us-east-1
awslogs-stream-prefix: mysql
volumes:
test:
```
ecs-params.yml:
```
version: 1
services:
wordpress:
essential: true
cpu_shares: 102
mem_limit: 30g
mem_reservation: 22m
```
resulting task definition:
```
{
{
"logConfiguration": {
"logDriver": "awslogs",
"options": { …
```
=> Wire up top-level Volumes for Compose 3

ecs-cli/modules/cli/compose/adapter/convert.go, ecs-cli/modules/cli/compose/adapter/convert_test.go, ecs-cli/modules/cli/compose/logger/logger.go, ecs-cli/modules/cli/compose/project/project_parseV1V2.go, ecs-cli/modules/cli/compose/project/project_parseV3.go
`make` and `make test` succeed
example v3 docker-compose.yml:
```
version: '3'
services:
web:
image: httpd
command: echo "hello world"
devices:  # unsupported
- "/dev/test"
pid: "wont-work" # unsupported
dns:
- 8.8.8.8
- 9.9.9.9
ports:
- "80:80"
ulimits:
nice: 6505
rss:
soft: 2000
hard: 4000
```
ecs-cli compose result:
```
$~\testUnsupported> ..\..\Documents\GO\src\github.com\aws\amazon-ecs-cli\bin\local\ecs-cli.exe compose create
WARN[0000] Skipping unsupported YAML option for service...  option name=devices service name=web
WARN[0000] Skipping unsupported YAML option for service...  option name=pid service name=web
INFO[0000] Using ECS task definition                     TaskDefinition="testUnsupported:5"
```
example v2 docker-compose.yml:
```
version: '2'
services:
web:
image: httpd …
```
=> Log warning for unsupported v3 compose options

ecs-cli/modules/cli/compose/project/project_test.go, ecs-cli/modules/utils/compose/ecs_params_reader.go
This adds support and a test for environment variables in ecs-params.yml.
It is a basic set of support for variables in the `$VAR` and `${VAR}` format.
=> Add support for environment variables in ecs-params.yml - Issue #530

ecs-cli/modules/cli/compose/project/project_parseV3_test.go
Refactor parseV3_test to not rely on docker/cli abstractions or conversion helper methods.
--
=> Refactor parseV3 tests

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_helper.go, ecs-cli/modules/cli/compose/entity/service/service_test.go
*Issue #, if available:* #79 
*Description of changes:* Insert a `waitForServiceDescribable()` in `Up()`
=> Add waiter for service creation - Fix for issue 79

ecs-cli/modules/cli/compose/project/project_parseV3.go, ecs-cli/modules/cli/compose/project/project_parseV3_test.go
Addresses issue #537
Pass map of local env vars into docker to be interpolated into compose project.
docker-compose.yml:
```
version: '3'
services:
test:
image: "$MY_IMAGE"
environment:
- WEB_VAR1=myvar
- PROC_REV=${PROCESSOR_REVISION}
```
"compose create" output:
```
$~\v3envVarsNoWork> ..\..\Documents\GO\src\github.com\aws\amazon-ecs-cli\bin\local\ecs-cli.exe compose create
INFO[0000] Using ECS task definition                     TaskDefinition="v3envVarsNoWork:12"
```
resulting task def:
```
{
{
"cpu": 0,
"environment": [
{
"name": "PROC_REV",
"value": "3d04"    // FROM ENV VAR
},
{
"name": "WEB_VAR1",
"value": "myvar"
}
],
"memory": 512,
"image": "nginx",   // FROM ENV VAR
"name": "test"
}
],
"family": "v3envVarsNoWork",
}
```
--
By submitting this pull …
=> Pass local environment into parseV3, fixes #537

ecs-cli/modules/cli/compose/adapter/convert.go, ecs-cli/modules/cli/compose/adapter/convert_test.go, ecs-cli/modules/clients/aws/ecs/client.go
*Description of changes:* [Range over map](https://github.com/aws/amazon-ecs-cli/blob/c7335b0259cc1fe526b751d7bc540730e09df2c7/ecs-cli/modules/compose/ecs/utils/convert_task_definition.go#L48) produces a nondeterministic ordering of container defs, thereby requiring task definition cache keys (the "tdcache") to sort on them (lest the cli mistakenly believe them to be changed, which remains relatively innocuous). 
=> In hashing task definitions, also sort containers by Name

ecs-cli/modules/cli/compose/adapter/containerconfig.go, ecs-cli/modules/cli/compose/adapter/convert.go, ecs-cli/modules/cli/compose/adapter/convert_test.go, ecs-cli/modules/cli/compose/logger/logger.go, ecs-cli/modules/cli/compose/project/project_parseV3.go, ecs-cli/modules/cli/compose/project/project_parseV3_test.go, ecs-cli/modules/utils/compose/convert_task_definition.go
#472 
Support the `healthcheck` field in Docker Compose v3. Note that `start_period` is not supported as this field was adding compose 3.4, and the ECS CLI does not support minor versions of compose.
=> Support container health check in Compose 3

ecs-cli/modules/clients/aws/cloudformation/template.go
Previously, cluster up would fail in cn-northwest-1 because the service
principal was not resolving correctly. This adds that region to the CFN
template.
Fixes #552
=> Add cn-northwest-1 to CFN template

ecs-cli/modules/cli/compose/project/project_parseV1V2.go, ecs-cli/modules/cli/compose/project/project_parseV1V2_test.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go
Previously, specifying memory reservation without memory limit would
cause a validation error. This fix allows either value to be specified
without the other, in either docker compose or ecs-params.
Fixes #546
=> Fix memory limit validation for compose 3

ecs-cli/modules/cli/compose/container/container.go, ecs-cli/modules/cli/compose/container/container_test.go
Show container health check status in ps command; simply returns the value returned by the ECS API (UNKNOWN if there isn't a health check, HEALTHY vs UNHEALTHY depending on the status).
```
$ ecs-cli ps --cluster compose3 --region eu-west-1
Name                                             State    Ports                      TaskDefinition       Health
afd7f8a0-3813-4e1a-9d9e-ca7e9d1fcfbb/wordpress   RUNNING  36.253.177.221:80->80/tcp  compose3:7           HEALTHY
dca67e02-68ca-4507-b194-a47239b5e7a9/wordpress   RUNNING  37.234.146.14:80->80/tcp   healthcheck:3        UNKNOWN
dca67e02-68ca-4507-b194-a47239b5e7a9/redis       RUNNING                             healthcheck:3        HEALTHY
feb6e10e-3385-4c9b-a6cb-787cc8e90dda/sample-app  RUNNING …
```
=> Show container health check status in ps command

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/mock/client.go
Previously, ECSClient#CreateService took many parameters. This made it
difficult to add new fields to the call. This changes the method to take
a request object that has the relevant fields pre-populated elsewhere.
=> Refactor CreateService

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/clients/aws/cloudformation/client.go, ecs-cli/modules/clients/aws/cloudformation/cluster_template.go, ecs-cli/modules/clients/aws/cloudformation/mock/client.go, ecs-cli/modules/clients/aws/cloudformation/params.go, ecs-cli/modules/clients/aws/cloudformation/params_test.go, ecs-cli/modules/clients/aws/cloudformation/private_namespace_template.go, ecs-cli/modules/clients/aws/cloudformation/sds_template.go
Refactored CloudFormation client and params to be generic so that they can be used by the service discovery implementation- previously they were specific to the cluster up workflow. Also added the CFN templates for private dns namespace and service discovery service.
=> Service Discovery: Refactor CFN Client and add SD CFN templates

ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/ecs_params_reader_test.go
Add support for `RepositoryCredentials.CredentialsParameter` to ecs-params.yml
docker-compose.yml:
```
version: '3'
services:
wordpress:
image: httpd
ports:
- "80:80"
```
ecs-params.yml:
```
version: 1
task_execution_role: ecsTaskExecutionRole
services:
wordpress:
repository_credentials:
credentials_parameter: arn:aws:secretsmanager:XXXXXXXXXX:secret:XXXXXXXX
cpu_shares: 27
mem_limit: 524288003
```
CMD output:
```
$~\credParamTest> ..\..\Documents\GO\src\github.com\aws\amazon-ecs-cli\bin\local\ecs-cli.exe compose create
INFO[0000] Using ECS task definition                     TaskDefinition="credParamTest:5"
```
Created task def:
```
{
"executionRoleArn": "arn:aws:iam::XXXXXXXXX:role/ecsTaskExecutionRole",
{
"portMappings": [
{
"hostPort": 80, …
```
=> Add support for credentials_parameter

ecs-cli/modules/version/gen/version-gen.go
=> Ensure git hash in ecs-cli --version is always 7 characters

ecs-cli/modules/cli/compose/compose_app.go, ecs-cli/modules/cli/compose/entity/task/task.go, ecs-cli/modules/cli/compose/entity/task/task_test.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/client_test.go, ecs-cli/modules/clients/aws/ecs/mock/client.go
Command Overrides are still supported via `compose run`, but this simplifies some of the code in our ECSClient wrapper.
=> Remove RunTaskWithOverrides from ECS Client

README.md, ecs-cli/modules/cli/compose/entity/entity_helper.go, ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/cli/compose/entity/task/task.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/client_test.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/ecs_params_reader_test.go
Supports specifying task placement strategies and placement constraints via `ecs-params` on `compose up` and `compose service up`. Also adds new `--force update` or `-u` flag on `compose up` to ensure latest `run_params` are being run (for updating placement constraints).
Closes #515 
Closes #212
=> Support task placement via ecs-params

ecs-cli/modules/clients/aws/cloudformation/cluster_template.go
In order to [enable DNS](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html), the VPC level settings `EnableDNSSupport` and `EnableDNSHostnames` must both be set to true. Currently, VPCs created with ecs-cli up have `EnableDNSHostnames` set to false (`EnableDNSSupport` defaults to true). This change explicitly sets both fields to true. This change will also bring the ECS CLI in line with the ECS Console, which creates clusters with both settings set to true.
=> Service Discovery: Enable DNS in VPCs created by the ECS CLI

ecs-cli/main.go, ecs-cli/modules/cli/regcreds/regcreds_app.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/regcreds/regcreds_command.go, ecs-cli/modules/utils/regcreds/creds_input_reader.go, ecs-cli/modules/utils/regcreds/creds_input_reader_test.go
Add new "registry-creds" cmd and read in file input.
Test output:
inputFile.yml:
```
version: 1
registry_credentials:
quay.io:
secret_manager_arn: aws:arn:secretsmanager:secret/repocreds-776ytg
username: ${USERNAME}
password: myl337p4$$w0rd!
kms_key_id: aws:arn:kms:key/iuytre-jhgfd
container_names:
- nginx-custom
- logging
```
CMD output:
```
$~\GO\src\github.com\aws\amazon-ecs-cli> ./bin/local/ecs-cli.exe registry-creds up --file inputFile.yml
?[36mINFO?[0m[0000] Read creds input: &{Version:1 RegistryCredentials:map[quay.io:{SecretManagerARN:aws:arn:secretsmanager:secret/repocreds-776ytg Username:[REDACTED] Password:myl337p4$$w0rd!<bz* KmdKeyID:aws:arn:kms:key/iuytre-jhgfd ContainerNames:[nginx-custom logging]}]}
```
--
By submitting this pull request, I confirm that my contribution is …
=> Add registry-creds cmd and creds_input_reader, tests

README.md, ecs-cli/Gopkg.lock, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/ecs_params_reader_test.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/version.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/api.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/errors.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ssm/errors.go, ecs-cli/vendor/github.com/docker/docker/integration-cli/fixtures/https/ca.pem, ecs-cli/vendor/github.com/docker/docker/integration-cli/fixtures/https/client-cert.pem, ecs-cli/vendor/github.com/docker/docker/integration-cli/fixtures/https/client-key.pem, ecs-cli/vendor/github.com/docker/docker/integration-cli/fixtures/https/server-cert.pem, ecs-cli/vendor/github.com/docker/docker/integration-cli/fixtures/https/server-key.pem, ecs-cli/vendor/github.com/docker/docker/project/CONTRIBUTING.md
=> Support Docker Volume Configuration in ECS Params

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_app.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_app_test.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_helper.go, ecs-cli/modules/clients/aws/route53/servicediscovery_client.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/ecs_params_reader_test.go
Ties everything together from previous PRs:
- read all ECS Params and flags input for SD creation
- merge all inputs together and validate
- find existing namespace ID if possible
=> Service Discovery: Full Create Workflow

ecs-cli/modules/cli/configure/migrate.go, ecs-cli/modules/commands/configure/configure_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/utils/utils.go
Pull "amazon-ecs-cli-setup-" prefix out as a constant, reference where previously used as string value.
--
=> Move resource prefix to utils package

ecs-cli/modules/cli/regcreds/regcreds_app.go, ecs-cli/modules/cli/regcreds/regcreds_app_test.go, ecs-cli/modules/clients/aws/secretsmanager/client.go, ecs-cli/modules/clients/aws/secretsmanager/client_test.go, ecs-cli/modules/clients/aws/secretsmanager/mock/client.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/regcreds/regcreds_command.go, ecs-cli/modules/utils/regcreds/creds_input_reader.go, ecs-cli/modules/utils/regcreds/creds_input_reader_test.go
Create or update secrets for registry credentials on `registry-creds up`.
`make` and `make test` pass.
createTest2.yml:
```yml
version: 1
registry_credentials:
fakeregistry-1.net:  # new reg credentials
username: ${USERNAME}
password: ${PASSWORD}
kms_key_id: arn:aws:kms:[REDACTED]
container_names:
- web-app
fakeregistry-2.net: # existing registry secret
secret_manager_arn: arn:aws:secretsmanager:[REDACTED]:secret:amazon-ecs-cli-setup-fakeregistry-2.net-RKAB66
container_names:
- metrics
somemoarreg.io: # existing registry secret, recreation attempt (arn not named; will be found via lookup)
username: ${USERNAME}
password: ${PASSWORD2}
container_names:
- test
- logging
```
cmd output (NOTE order of credential entries not retained):
```
$~\Documents\GO\src\github.com\aws\amazon-ecs-cli> …
```
=> Add secret creation to 'registry-creds up' cmd

ecs-cli/modules/cli/regcreds/regcreds_app.go, ecs-cli/modules/cli/regcreds/regcreds_app_test.go
* Use centralize prefix const from #604 
* fix generateSecretString() so it produces valid secret JSON and add tests
--
=> Use utils.ECSCLIResourcePrefix, fix secret string generation

README.md, ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/cli/cluster/userdata/user_data.go, ecs-cli/modules/cli/cluster/userdata/user_data_test.go, ecs-cli/modules/clients/aws/cloudformation/params.go, ecs-cli/modules/clients/aws/cloudformation/template.go, ecs-cli/modules/commands/cluster/cluster_command.go, ecs-cli/modules/commands/flags/flags.go
Features:
- multiple user data files can be specified with `--extra-user-data` (same as `--file` in Compose)
- all user data is concatenated into a single MIME Multipart archive, which includes a CLI generated shell script to join the ECS Cluster
- the passed in user data file can be a MIME Multipart archive; the CLI retains all header/content type information for each part in the archive.
- the CLI supports all user data formats (shell scripts and cloud-init directives)
- in the final multipart archive, all files that didn't include content type declarations will be declared as `text/plain`. This is safe because cloud-init will interpret its type based upon its content (I've verified this through a good amount of real world testing and also by reading the cloud-init code). 
*Issue #, if …
=> Add support for custom user data with the ECS CLI

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_app.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_app_test.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_helper.go, ecs-cli/modules/clients/aws/cloudformation/client.go, ecs-cli/modules/clients/aws/route53/client_test.go, ecs-cli/modules/clients/aws/route53/servicediscovery_client.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/flags/flags.go
Update and delete for Service Discovery. Only the SDS values DNS TTL and Failure Threshold can be updated, making update pretty boring.
=> Service Discovery - Update and Delete

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/clients/aws/cloudformation/params.go, ecs-cli/modules/clients/aws/cloudformation/template.go, ecs-cli/modules/commands/cluster/cluster_command.go, ecs-cli/modules/commands/flags/flags.go
*Issue #396*
This PR add support for EC2 Spot instances.
Main change is to update CloudFormation to add parameter `SpotPrice`.
If this parameter is greater than `0` then we specify a SpotPrice in LaunchConfiguration, resulting in creation of a Spot Request.
All the other changes, are 'plumbing' to get this option `spot-price` on command line when creating cluster
=> Add support for EC2 Spot instances

ecs-cli/modules/cli/servicediscovery/servicediscovery_helper.go
Int64 values weren't getting displayed properly
=> Service Discovery - Fix Override Warning Message

ecs-cli/modules/cli/servicediscovery/servicediscovery_app_test.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_helper.go
Bug fix- set Service Discovery Service name from the ECS Params input (if it was specified). The previous incorrect behavior was that the default value (SDS name is the same as the ECS Service name) was always set no matter what.
=> Service Discovery - Set SDS Name from ECS Params

ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go
Previously, `convert_task_definition` was taking in 6 distinct parameters. Rather than continue to add on to these in the future, I refactored the function to take in a struct with all the "ingredients" necessary to convert compose inputs to a task def.
--
=> Refactor convert_task_definition to use params struct

ecs-cli/Gopkg.lock, ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/cli/compose/project/project_test.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/regcredio/creds_readers.go, ecs-cli/modules/utils/regcredio/creds_readers_test.go, ecs-cli/modules/utils/regcredio/creds_writers.go, ecs-cli/modules/utils/regcredio/creds_writers_test.go, ecs-cli/modules/utils/regcredio/types.go
ecs-registry-creds_20181017T180501Z.yml:
```
version: "1"
registry_credential_outputs:
task_execution_role: "myCredRole0"
container_credentials:
fakeregistry-2.net:
credential_parameter: arn:aws:secretsmanager:us-west-2:#########:secret:amazon-ecs-cli-setup-fakeregistry-2.net-RKAB66
container_names:
- wordpress
myacct.somemoarreg.io/someteam/mine:
credential_parameter: arn:aws:secretsmanager:us-west-2:#########:secret:amazon-ecs-cli-setup-myacct.somemoarreg.io/someteam/mine-yarTSn
kms_key_id: arn:aws:kms:us-west-2:#########:key/c58cf9b5-###-4657-8bee-a89f66d27c00
```
docker-compose.yml:
```
version: '3'
services:
wordpress:
image: fakeregistry-2.net-RKAB66/httpd
ports:
- "80:80"
```
ecs-params.yml:
```
version: 1
task_execution_role: ecsTaskExecutionRole
ecs_network_mode: …
```
=>  Integrate registry creds into 'compose'

ecs-cli/modules/cli/cluster/cluster_app.go
Fixes a minor bug: previously errors weren't caught on from the `AddFile` method for user data. This meant that something like this will erroneously succeed:
```
ecs-cli up --capability-iam --extra-user-data some_file_that_doesnt_exit
```
This PR fixes the issue by checking the error.
=> Bug fix: catch errors from UserDataBuilder.AddFile

ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/cli/compose/project/project_test.go, ecs-cli/modules/cli/regcreds/regcreds_app.go, ecs-cli/modules/commands/regcreds/regcreds_command.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/regcredio/creds_readers_test.go, ecs-cli/modules/utils/regcredio/types.go
* Add optional region & profile flags to `registry-creds up`
* Add a warning when regcred containers present but not used with `compose`
* Add a warning re: no container names to `registry-creds up`
* Add messaging re: deleting sensitive input file
* Rename some things
* Cap max # of regcred entries to 10 on `registry-creds up`
warning on unused regcred containers with `compose`:
```
$~\regCredTest> ../../Documents/GO/src/github.com/aws/amazon-ecs-cli/bin/local/ecs-cli.exe compose create
INFO[0000] Found ecs-registry-creds file .\ecs-registry-creds_20181024T175954Z.yml
INFO[0000] Using ecs-registry-creds value arn:aws:secretsmanager:ap-northeast-1:##########:secret:amazon-ecs-cli-setup-dockerhub-YXVBuX  container name=web option name=credentials_parameter
WARN[0000] Containers listed with …
```
=> Improve messaging and validation for registry creds

ecs-cli/modules/clients/aws/cloudwatchlogs/client.go, ecs-cli/modules/clients/aws/cloudwatchlogs/client_test.go
Fixes #644, see issue for description of the issue.
=> Bug fix: log client creation doesn't change region in session

README.md, ecs-cli/Gopkg.lock, ecs-cli/modules/cli/compose/entity/entity_helper.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/ecs_params_reader_test.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/version.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ssm/api.go
=> Add support for pidMode and ipcMode

ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/compose/reconcile_container_def.go
* Resolves #570 , #606
Previously, if no `mem_limit` was set on a container, the ecs-cli would default it to 512mb, even if task size memory was set. Additionally, if `mem_reservation` was set but `mem_limit` was not, the latter would be set to the same value. 
This change leaves `mem_limit` unset (nil) in both cases.
docker-compose.yml
```
version: '2'
services:
wordpress:
image: wordpress
ports:
- "80:80"
```
ecs-params.yml
```
version: 1
ecs_network_mode: bridge
task_size:
cpu_limit: 250
mem_limit: 1gb
```
CMD out put
```
$> ~\ecs-cli.exe compose create
INFO[0000] Using ECS task definition                     TaskDefinition="wordpress-test:6"
```
resulting task definition
```
{
{
"portMappings": [
{
"hostPort": 80,
"protocol": "tcp", …
```
=> Allow container mem_limit to be null

ecs-cli/modules/cli/compose/logger/logger.go
Currently, ecs-cli reports warnings about `extends` field.
```yaml
version: '2'
services:
web:
extends:
file: base.yml
service: base
command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
ports:
- "3000"
```
```
$ ecs-cli compose --cluster app --ecs-params ecs/ecs-params.yml -f ecs/web.yml -p web service up --deployment-max-percent=200 --deployment-min-healthy-percent=100
time="2018-12-04T02:58:18Z" level=warning msg="Skipping unsupported YAML option for service..." option name=extends service name=web
```
However, the `extends` field seems to be supported by ecs-cli.
=> Add `extends` to supportedComposeV1V2YamlOptions

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/flags/flags.go
This partially addresses #540 
Adding optional `--scheduling-strategy` flag  on `ecs-cli compose service create` and `ecs-cli compose service up` commands:
`--scheduling-strategy value                          [Optional] Specifies the scheduling strategy type. Options: REPLICA (default) or DAEMON.` 
=> Adding --scheduling-strategy (REPLICA or DAEMON) option

README.md, ecs-cli/modules/cli/image/image_app.go, ecs-cli/modules/cli/image/image_app_test.go, ecs-cli/modules/clients/aws/ecr/client.go, ecs-cli/modules/clients/aws/ecr/client_test.go, ecs-cli/modules/commands/cluster/cluster_command.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/image/image_command.go, ecs-cli/modules/config/config_v1.go
Related to https://github.com/awslabs/amazon-ecr-credential-helper/pull/127/files
=> Support FIPS endpoint

ecs-cli/modules/cli/logs/logs_app.go, ecs-cli/modules/cli/logs/logs_app_test.go
=> Allow --create-log-groups when only some containers use awslogs

Makefile, ecs-cli/integ/README.md, ecs-cli/integ/cmd_ps.go/ps_test.go, ecs-cli/integ/resources/ecs_cli_integ_template.json, ecs-cli/integ/runner.go
Adding integration test wiring, README, and test for `ps` command.
```
$>  /usr/bin/make integ-test
Building ecs-cli...
./scripts/build_binary.sh ./bin/local
Running integration tests...
go test -tags integ -v ./ecs-cli/integ/...
?   	github.com/aws/amazon-ecs-cli/ecs-cli/integ	[no test files]
=== RUN   TestCmd_PS
--- PASS: TestCmd_PS (0.74s)
PASS
ok  	github.com/aws/amazon-ecs-cli/ecs-cli/integ/cmd_ps.go	0.748s
$>
```
```
PS C:\...\GO\src\github.com\aws\amazon-ecs-cli> go build -installsuffix cgo -a -ldflags '-s' -o ./bin/local/ecs-cli.exe ./ecs-cli/
PS C:\...\GO\src\github.com\aws\amazon-ecs-cli>
PS C:\...\GO\src\github.com\aws\amazon-ecs-cli> go test -tags integ -v ./ecs-cli/integ/...
?       github.com/aws/amazon-ecs-cli/ecs-cli/integ     [no test files]
=== RUN   TestCmd_PS
--- PASS: …
```
=> Add Integ test resources, "ps" test

README.md, ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_app.go, ecs-cli/modules/cli/servicediscovery/servicediscovery_app_test.go, ecs-cli/modules/clients/aws/cloudformation/client.go, ecs-cli/modules/clients/aws/cloudformation/cluster_template.go, ecs-cli/modules/clients/aws/cloudformation/mock/client.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/mock/client.go, ecs-cli/modules/commands/cluster/cluster_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/utils/utils.go
#670
Support tagging for resources created by `ecs-cli up`, with the exception of:
- Container Instances (more complicated, will be in a separate PR - EC2 Instances are supported in this PR tho)
- Instance IAM Role (CloudFormation doesn't support tags)
- Instance Profile (Doesn't support tagging)
- Autoscaling Launch Config (Doesn't support tagging)
=> Resource Tagging in `ecs-cli up`

ecs-cli/modules/cli/regcreds/create_task_execution_role_test.go, ecs-cli/modules/cli/regcreds/regcreds_app_helpers.go
Previously, ARN partition was always being set as "aws". Fixed this and added unit tests for role creation in diff partitions.
--
=> Fix getExecutionRolePolicyARN() in regcreds

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/compose/entity/entity.go, ecs-cli/modules/cli/compose/entity/entity_helper.go, ecs-cli/modules/cli/compose/entity/mock/entity.go, ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/cli/compose/entity/task/task.go, ecs-cli/modules/cli/compose/entity/task/task_test.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/mock/client.go, ecs-cli/modules/commands/compose/compose_command.go, ecs-cli/modules/commands/compose/service/compose_service_command.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/utils/utils.go, ecs-cli/modules/utils/utils_test.go
Added `--tags` to compose commands. Also:
- Tags propagate from a Service's Task Definition to its Tasks
- ECS Managed Tags (Cluster name and Service name tags) are enabled by default. This can be turned off with `--disable-ecs-managed-tags`. Rationale: tags are free and useful, might as well make using them the default, rather than an annoyingly long flag that must always be added to each command.
=> Resource Tagging and ECS Managed Tags in Compose Commands

ecs-cli/modules/cli/regcreds/create_task_execution_role.go, ecs-cli/modules/cli/regcreds/create_task_execution_role_test.go, ecs-cli/modules/cli/regcreds/regcreds_app.go, ecs-cli/modules/cli/regcreds/regcreds_app_test.go, ecs-cli/modules/clients/aws/iam/client.go, ecs-cli/modules/clients/aws/iam/mock/client.go, ecs-cli/modules/commands/regcreds/regcreds_command.go
Tag SM secrets and new IAM roles. (IAM is not supported by the standalone resource tagging API, so tagging can only be supported during role creation).
=> Resource tagging in the registry-creds up command

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/cli/cluster/userdata/user_data.go, ecs-cli/modules/cli/cluster/userdata/user_data_test.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/ecs/mock/client.go
This part is a bit thorny because it requires opt-in to the new long arn format.
=> Support Container Instance Tagging

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/cli/compose/entity/task/task.go, ecs-cli/modules/cli/compose/entity/task/task_test.go
Bugfix: ECS Managed tags are enabled by default, but only when long ARN formats are enabled.
Enhancement: Propagate tags is always set on Service (if long ARN is supported) even if no tags are present at creation. This ensures that if tags are later added, they will propagate to the tasks.
=> Tagging bugfix + Enhancement

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/cli/cluster/userdata/user_data.go, ecs-cli/modules/cli/cluster/userdata/user_data_test.go, ecs-cli/modules/config/command_config_test.go
The previous way of doing tagging wasn't very robust; the ECS Agent can fail to uptake tags from the EC2 instance. So we're doing this instead.
Related to: https://github.com/aws/amazon-ecs-agent/issues/1935
=> Support container instance tagging via tags in user data ✈ 

ecs-cli/modules/cli/compose/adapter/containerconfig.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/reconcile_container_def.go
https://github.com/aws/amazon-ecs-cli/issues/716
Allow appending `init_process_enabled: <bool>` to services defined in ecs-params.yml to toggle init flag for services in task definitions.
=>  Allow init_process_enabled bool from ecs_params

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/clients/aws/amimetadata/client.go, ecs-cli/modules/clients/aws/amimetadata/client_test.go, ecs-cli/modules/clients/aws/cloudformation/cluster_template.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/reconcile_container_def.go
*Issue #, if available:* 729
*Description of changes:* Add GPU support to the CLI by:
1. Allowing p2* and p3* instances to be added to the cluster 
2. Adding optional `gpu` parameter in `ecs-params.yml` to place containers on hosts with GPUs
_Note that these changes got reviewed and approved already in [pull/750](https://github.com/aws/amazon-ecs-cli/pull/750) and [pull/743](https://github.com/aws/amazon-ecs-cli/pull/743)
=> Merge gpu branch into dev

.travis.yml, Makefile
Support build 1.12.x
Golang 1.12 requires GOCACHE, therefore add environment variable.
=> support build 1.12.x

.github/PULL_REQUEST_TEMPLATE.md
=> Update PR template with task list for testing and documentation

Makefile, ecs-cli/integ/cfn/cfn.go, ecs-cli/integ/cmd/compose.go, ecs-cli/integ/cmd/configure.go, ecs-cli/integ/cmd/ps.go, ecs-cli/integ/cmd/up.go, ecs-cli/integ/e2e/ec2_task_test.go, ecs-cli/integ/e2e/fargate_service_test.go, ecs-cli/integ/ecs/ecs.go, ecs-cli/integ/runner.go
**Description of changes**: Add integration tests that follow our EC2 tutorial (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cli-tutorial-ec2.html)
----
**Testing**  
----
=> Add integration tests that follow our EC2 tutorial

Makefile, buildspec.yml, ecs-cli/integ/README.md, ecs-cli/integ/cmd/compose.go, ecs-cli/integ/cmd/ps.go, ecs-cli/integ/runner.go, ecs-cli/integ/stdout/stdout.go, ecs-cli/main.go, ecs-cli/main_test.go
**Description of changes**: `make integ-test` now outputs our code coverage. For example, the fargate tutorial e2e test covers 29.2% of our statements.
----
**Testing**  
----
=> Generate coverage statistics for integration tests

README.md
The V1 Path format will eventually be deprecated: https://forums.aws.amazon.com/ann.jspa?annID=6776
**Testing**  
- [N/A ] Unit tests passed
- [N/A ] Integration tests passed
- [N/A ] Unit tests added for new functionality
- [N/A ] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
- [N/A ] Link to issue or PR for the integration tests: 
- [ √] Contacted our doc writer
- [ √] Updated our README
----
=> Update S3 URLs to V2 path format

ecs-cli/main.go, ecs-cli/modules/cli/local/local_app.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/local/local_command.go
=> Scaffolding for local create

ecs-cli/integ/e2e/local_test.go, ecs-cli/modules/cli/local/create_app.go, ecs-cli/modules/cli/local/docker.go, ecs-cli/modules/cli/local/local_app.go, ecs-cli/modules/cli/local/ps_app.go, ecs-cli/modules/cli/local/stop_app.go, ecs-cli/modules/cli/local/up_app.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/local/local_command.go
**Description of changes**: Lists the running containers part of the ECS tasks running locally.
----
**Testing**  
----
=> Support "local ps" to list running local ECS task containers

buildspec.yml, ecs-cli/integ/e2e/local_test.go, ecs-cli/integ/runner.go, ecs-cli/modules/cli/local/docker/docker.go, ecs-cli/modules/cli/local/down_app.go, ecs-cli/modules/cli/local/network/setup.go, ecs-cli/modules/cli/local/network/teardown.go, ecs-cli/modules/cli/local/network/teardown_test.go, ecs-cli/modules/cli/local/ps_app.go, ecs-cli/modules/cli/local/up_app.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/local/local_command.go
**Description of changes**: `ecs-cli local down` stops a running local task. If the stopped task is the last running ECS local task, then also teardown the network.
----
**Testing**  
----
=> Support "local down" to stop a running local task

ecs-cli/integ/e2e/local_test.go, ecs-cli/integ/runner.go, ecs-cli/integ/stdout/stdout.go, ecs-cli/modules/cli/local/down_app.go, ecs-cli/modules/cli/local/ps_app.go, ecs-cli/modules/commands/local/local_command.go
**Description of changes**: The command `local ps` will by default output the containers in the `docker-compose.local.yml` file.   
If the `--all` flag is provided, then all local ECS task containers are printed.
----
**Testing**  
----
=> Update "local ps" to default to compose project

buildspec.yml, ecs-cli/modules/cli/local/docker/docker.go, ecs-cli/modules/cli/local/network/mock_network/setup.go, ecs-cli/modules/cli/local/network/setup.go, ecs-cli/modules/cli/local/network/setup_test.go
**Description of changes**:  
As a user that's running `ecs-cli local up` and doesn't have the [amazon/amazon-ecs-local-container-endpoints](https://hub.docker.com/r/amazon/amazon-ecs-local-container-endpoints) downloaded locally.  
I want `ecs-cli local up` to pull the image for me.  
So that I don't have to pull the image myself.
----
**Testing**  
- [N/A] ~~Link to issue or PR for the integration tests:~~ The integ tests need to pull the image to pass.
----
=> Pull Endpoints image if it doesn't exist

Makefile
Enabled the race detector when `make test` is executed.
And just for fun, I timed the `make test` command before and after this code change, there's essentially no difference:
```
Before:
real    1m14.350s
user    2m24.599s
sys     0m31.100s
After:
real    1m15.237s
user    2m29.455s
sys     0m31.182s
```
**Testing**  
- [Y] Unit tests passed
----
By submitting this pull request, I confirm that my …
=> Enabled race detector during the execution of unit tests

ecs-cli/modules/cli/local/project/project.go
=> fixed #796

ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/converter/converter_test.go
**Issue #, if available**: [#797](https://github.com/aws/amazon-ecs-cli/issues/797)
**Description of changes**: This is the first part of [#797](https://github.com/aws/amazon-ecs-cli/issues/797). See the rest of the issue on how these labels can be used by "local up" to pass the
values of the secrets to the containers.
----
**Testing**  
----
=> Add the ssm or secretsmanager ARN as Docker Labels to each service

ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/converter/converter_test.go
Changed the networks of local containers, so that the networks of local containers are set to external `ecs-local-network`, and can talk with the `LocalEndpointsContainer`.
Fixed #802 
----
**Testing**  
----
=> Change network of local containers to "ecs-local-network"

ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/create_app.go, ecs-cli/modules/cli/local/project/project.go
Added `local create` metadata to local Compose file. Metadata `ecsLocalTaskDefType` and `ecsLocalTaskDefVal` are added.
Fixed #801 
----
**Testing**  
----
=> Add `local create` metadata to local Compose file

ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/create_app.go, ecs-cli/modules/cli/local/down_app.go, ecs-cli/modules/cli/local/localproject/project.go, ecs-cli/modules/cli/local/ps_app.go
Removed duplicate definition for default output docker compose file name, `TaskDefinitionLabelType`, `TaskDefinitionLabelValue` etc. And added comments for exported constants.
----
**Testing**  
----
=> Deleted duplicate const definition and added comment for const

Makefile, ecs-cli/integ/cmd/compose.go, ecs-cli/integ/cmd/up.go
N/A
This change brings a fix (https://github.com/aws/amazon-ecs-cli/pull/789/commits/520d17719be12bec1cf797dcabb677d48f47761d) that was already merged on the `ecs-local` branch to the `dev` branch. The main reason behind the change is because I want to be able to run integ tests on some new changes I'm adding to the `dev` branch.
----
**Testing**  
- [N/A] Contacted our doc …
=> fix `TestCreateClusterWithFargateService` integration test

ecs-cli/integ/e2e/ec2_task_test.go, ecs-cli/integ/e2e/fargate_service_test.go, ecs-cli/modules/cli/compose/adapter/containerconfig.go, ecs-cli/modules/cli/compose/adapter/convert.go, ecs-cli/modules/cli/compose/adapter/convert_test.go, ecs-cli/modules/cli/compose/logger/logger.go, ecs-cli/modules/cli/compose/project/project_parseV1V2.go, ecs-cli/modules/cli/compose/project/project_parseV1V2_test.go, ecs-cli/modules/cli/compose/project/project_parseV3.go, ecs-cli/modules/cli/compose/project/project_parseV3_test.go, ecs-cli/modules/utils/compose/reconcile_container_def.go
Closes #787 
Added the support for the `StopTimeout` field, which maps to the `stop_grace_period` in Docker compose.
----
**Testing**  
**Manual Testing**
Before code change
```
$ cat docker-compose.yml
version: '2'
services:
web:
image: amazon/amazon-ecs-sample
ports:
- "80:80"
stop_grace_period: 1m15s
$ ./ecs-cli compose up --cluster chicken
WARN[0000] Skipping unsupported YAML option for service...  option name=stop_grace_period service name=web
INFO[0000] Using ECS task definition                     TaskDefinition="ecs-cli-tutorial:1"
INFO[0000] Starting container... …
```
=> Added support for the `StopTimeout` field in `ContainerDefinition`

ecs-cli/modules/cli/local/down_app.go, ecs-cli/modules/cli/local/ps_app.go, ecs-cli/modules/cli/local/up_app.go
#817 (#823)
Fixed the issue of swallowing error log details when ecs-cli local up/ps/down. Also #823 has the same problem resulting the difficulty for debugging.
**Testing**  
----
=> [local] fix swallowing error log details when ecs-cli local up/ps/down

ecs-cli/modules/cli/local/secrets/clients/clients.go, ecs-cli/modules/cli/local/secrets/clients/clients_test.go
**Issue #, if available**: https://github.com/aws/amazon-ecs-cli/issues/822
The `secrets/clients` previously used only `session.NewSession()` which ignores the `~/.aws/config` file and reads only from `$AWS_REGION`. This change leverages the `NewCommandConfig()` method to create a session that respect ECS CLI's order resolution for the region.
Furthermore, to follow best practices for sessions (https://docs.aws.amazon.com/sdk-for-go/api/aws/session/) we are caching them in the SSM client instead of re-creating them multiple times.
----
**Testing**  
----
By submitting this pull request, I confirm that my …
=> Use the ECS CLI's default region and cache the SSM clients per region

ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/converter/converter_test.go
Previously the containers lacked a way of retrieving credentials and metadata information from the Endpoints container. This change stores the information as environment variables on the container.
Addresses #810 
----
**Testing**  
----
=> Add env vars to retrieve creds and metadata from Endpoints container

ecs-cli/modules/cli/local/localproject/project.go
Issue #, if available:
#818 
Description of changes:
When running ecs-cli local create/up using a family name, it will print out which exact task definition revision is being used to generate local Docker compose file.
----
**Testing**  
----
=> added print out task definition revision

ecs-cli/modules/cli/local/localproject/project.go, ecs-cli/modules/cli/logs/logs_app.go, ecs-cli/modules/clients/aws/ecr/client.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/clients/aws/route53/servicediscovery_client.go, ecs-cli/modules/config/command_config.go, ecs-cli/modules/config/command_config_test.go, ecs-cli/modules/config/config_v1.go
Previously, passing a full task definition ARN to `local up` would not account for the region specified in the ARN and would default to the region configuration of the ECS client. This change enables local up to fetch and run a task definition from the correct region specified in its ARN.
Fixes #821 
----
**Testing**  
----
=> Read arn region

ecs-cli/modules/cli/local/create_app.go, ecs-cli/modules/cli/local/down_app.go, ecs-cli/modules/cli/local/localproject/project.go, ecs-cli/modules/cli/local/localproject/project_test.go, ecs-cli/modules/cli/local/options/options.go, ecs-cli/modules/cli/local/ps_app.go, ecs-cli/modules/cli/local/up_app.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/local/local_command.go
Add the `--task-def-compose` flag to `up`, `create`, and `down`.
Fixes https://github.com/aws/amazon-ecs-cli/issues/809
----
**Testing**  
----
=> Restructure local commands and flags

ecs-cli/modules/cli/compose/factory/factory.go, ecs-cli/modules/cli/compose/project/project_test.go, ecs-cli/modules/utils/compose/lookup.go
EnvironmentLookup is already implemented by the `project.NewProject()` in the libcompose library, which is called in `parseV1V2()`. In addition, as of 06/28/19, `.env` does not work with Compose V3 (#726) so this change should not affect any v3 feature.
----
**Testing**  
----
**Manual Testing**
Rebuilt `ecs-cli` with my change.
```
$ cat docker-compose.yml
version: '2'
services:
web:
image: amazon/amazon-ecs-sample:$TAG
ports:
- "80:80"
stop_grace_period: 1m15s
```
```
$ cat .env
TAG=1
```
You can see the `TAG` environment variable is …
=> Remove redundant environment lookup for Compose v1, v2

ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/converter/marshal.go, ecs-cli/modules/cli/local/converter/override.go, ecs-cli/modules/cli/local/converter/override_test.go, ecs-cli/modules/cli/local/localproject/project.go
**Issue #, if available**: Related to https://github.com/aws/amazon-ecs-cli/issues/831
**Description of changes**: Override the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable and `logging.driver` field for every service in the Compose file.
----
**Testing**  
----
=> Convert task definition to default Compose override config

ecs-cli/modules/cli/local/create_app.go, ecs-cli/modules/cli/local/localproject/project.go, ecs-cli/modules/cli/local/localproject/project_test.go
**Description of changes**: Writes a default `docker-compose.ecs-local.override.yml` if no `-o` flag is provided. Otherwise, creates a `{customName}.override.yml` file.
----
**Testing**  
----
=> Write an override compose file with local create

ecs-cli/integ/e2e/local_test.go, ecs-cli/modules/cli/local/ps_app.go, ecs-cli/modules/commands/local/local_command.go
**Description of changes**: The custom named Compose files already contain our labels `ecs-local.*` so there is no need to take `-c` as a flag.
----
**Testing**  
----
=> Remove --task-def-compose from local ps and down

ecs-cli/modules/cli/local/up_app.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/local/local_command.go
**Description of changes**: Added a `--add-overrides` flag that's passed down to docker-compose. This way users can specify additional override files besides the default one that we generate.
----
**Testing**  
----
=> Support override Compose files for "local up"

ecs-cli/modules/cli/local/localproject/project.go, ecs-cli/modules/cli/local/localproject/project_test.go, ecs-cli/modules/cli/local/ps_app.go, ecs-cli/modules/cli/local/up_app.go
Previously, specifying the `--file` flag on `local up`, `local ps` and `local down` would assume the file was only in the current directory the command was being run from. This would cause unexpected behavior when task definition files with the same name existed in different directories.
With this change, Local up, ps, and down will correctly recognize the file used to run containers by looking at the absolute path, which is stored in the metadata labels on the local project.
Fixes #834 
----
**Testing**  
----
=> Support using relative path when specifying task def file

ecs-cli/modules/cli/compose/adapter/convert.go, ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/converter/converter_test.go
Support bind mount volumes
Addresses #810 
----
**Testing**  
----
=> Support volumes

ecs-cli/modules/cli/local/ps_app.go
Fixes #869 
**Description of changes**: If we don't set `All: true` then containers that were stopped would not be listed and hence not removed when running `local down --all`.
----
**Testing**  
----
=> List all containers matching the ecs-local labels

ecs-cli/modules/cli/local/localproject/project.go
If the Compose override file already exists then we log it to the user and don't overwrite it.
Fixes #863
----
**Testing**  
----
=> Skip overwriting .override file if it already exists

ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/converter/converter_test.go
Compose file version is bumped to v3.4 and container with `startPeriod` set now can be started without erroring.
Fixes #868 
----
**Testing**  
----
=> Bump compose file version to v3.4

ecs-cli/modules/cli/local/converter/converter.go
When we convert a task def, if the log driver is set to
"awslogs", we convert that to use json-file localy (so customers
aren't surprised when their local testing logs don't end up in
CloudWatch).
This change updates the messaging when we do that.
New output:
```
INFO[0000] Task Definition network mode is ignored when running containers locally. Tasks will be run in the ecs-local-network.  networkMode=awsvpc
INFO[0000] awslogs log driver is ignored when running locally. Tasks will default to json-file instead. This can be changed in your compose override file.
INFO[0000] Successfully wrote docker-compose.ecs-local.yml
INFO[0000] Successfully wrote docker-compose.ecs-local.override.yml
```
Fixes #862 
----
**Testing**  
----
By submitting this pull request, I confirm …
=> Cleanup log messages for log driver conversions

ecs-cli/modules/cli/local/up_app.go
Set environment variable COMPOSE_IGNORE_ORPHANS so that the orphaned container checking is disabled.
Fixes #852
----
**Testing**  
----
=> Added env to suppress the orphaned checking

ecs-cli/modules/cli/local/up_app.go
Fixes #864
**Description of changes**: The progress of downloading an image is streamed to stdout whereas previously we would only spit the results at the end once the command finishes.
----
**Testing**  
----
=> Output progress of docker-compose --build

ecs-cli/modules/commands/local/local_command.go
fixes #874
Brings our CLI documentation in line with our actual AWS
documentation. The new documentation is from the --help command is output below.
```
NAME:
ecs-cli local up - Run containers locally from an ECS Task Definition. NOTE: Creates a docker-compose file in current directory and a ecs-local-network if one doesn't exist.
USAGE:
ecs-cli local up [command options] [arguments...]
OPTIONS:
--task-def-compose value, -c value  Specifies the filename value that contains the Docker Compose content to run locally.
--task-def-file value, -f value     Specifies the filename value containing the task definition JSON to convert and run locally.  If one is not specified, the ECS CLI will look for task-definition.json.
--task-def-remote value, -r value   Specifies the full Amazon Resource Name …
```
=> Update local help documentation to match AWS documentation

Makefile
Updated `make` target to correct reference to coverage tool.
----
**Testing**
- [N/A ] Link to issue or PR for the integration tests:
```
...
total:                                                      (statements)                    38.6% 
rm $TMPDIR/coverage* $TMPDIR/all.out 
[Container] 2019/06/05 21:28:36 Running command ./bin/local/ecs-cli.test 
...
PASS 
coverage: 2.3% of statements in ./ecs-cli/modules/... 
[Container] 2019/06/05 21:28:36 Phase complete: BUILD State: SUCCEEDED 
[Container] 2019/06/05 21:28:36 Phase context status code:  Message:  
[Container] 2019/06/05 21:28:36 Entering …
```
=> update MAKE target integ-test-run-with-coverage

.travis.yml
Because we live in the future
----
=> Remove go 1.9 from travis build

ecs-cli/modules/cli/local/up_app.go
* Fixes #892
----
**Testing**
- [N/A ] Link to issue or PR for the integration tests:
- [N/A ] Contacted our doc writer
- [N/A ] Updated our README
```
PS ~\go\src\github.com\aws\amazon-ecs-cli> ./bin/local/ecs-cli.exe local up -f ..\local_test\my-task-definition.json
?[36mINFO?[0m[0000] Task Definition network mode is ignored when running containers locally. Tasks will be run in the ecs-local-network.  ?[36mnetworkMode?[0m=awsvpc
docker-compose.ecs-local.yml file already exists. Do you want to write over this file? [y/N]
y
?[36mINFO?[0m[0002] docker-compose.ecs-local.override.yml already exists, skipping write. …
```
=> Pass in environment when running 'local up'

ecs-cli/modules/commands/cluster/cluster_command.go
Change help text for `--instance-role` flag in `up` cmd to reflect the fact we create a new instance profile.
```
PS ~\amazon-ecs-cli> ./bin/local/ecs-cli.exe up --help
NAME:
ecs-cli.exe up - Creates the ECS cluster (if it does not already exist) and the AWS resources required to set up the cluster.
USAGE:
ecs-cli.exe up [command options] [arguments...]
OPTIONS:
--capability-iam                  Acknowledges that this command may create IAM resources. Required if --instance-role is not specified. NOTE: Not applicable for launch type FARGATE or when creating an empty cluster.
--empty, -e                       [Optional] Specifies that an ECS cluster will be created with no resources.
--instance-role value             [Optional] Specifies a custom IAM Role for instances in your cluster. A …
```
=> Add new profile language to --instance-role help text

README.md, ecs-cli/modules/cli/compose/project/project.go, ecs-cli/modules/cli/compose/project/project_test.go, ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/ecs_params_reader_test.go
Fixes issue described in [this comment](https://github.com/aws/amazon-ecs-cli/pull/909#issuecomment-525497445). 
docker-compose.yml
```
version: '2'
services:
database:
image: httpd:2.4
ports:
- "80:80"
environment:
- ENV1=test
```
ecs-params.yml
```
version: 1
placement_constraints:
- type: memberOf
expression: "attribute:ecs.os-type == linux"
- type: memberOf
expression: "attribute:ecs.instance-type == t2.micro"
run_params:
task_placement:
constraints:
- type: memberOf
expression: "attribute:ecs.os-type == linux"
```
cmd output:
```
> ecs-cli.exe compose service up
[36mINFO[0m[0000] Using ECS task definition                     [36mTaskDefinition[0m="placement:5"
[36mINFO[0m[0000] Updated the ECS service with a new task definition. Old containers will be stopped …
```
=> Taskdef constraints

ecs-cli/integ/e2e/local_test.go
This commit adds functionality using the Docker SDK to verify that the
correct container images were started by local integration tests. 
It also adds line-by-line comparison of docker compose files generated by
ecs-cli local subcommands to a known valid template.
Finally, one new integration test is added to cover the default behavior of 
"ecs-cli local up" wherein a task definition is not specified.
Related to #772 (Integration tests for ecs-cli local)
----
**Testing**
- [✅] Unit tests passed
- [✅] Integration tests passed
- …
=> Add extra validation to ecs-cli local integ tests

ecs-cli/integ/e2e/local_test.go
See title. Fixes build failures in CodeBuild standard image 1.8.0 where latest client is too new.
----
**Testing**
----
=> Pin docker client for integ tests to 1.39

ecs-cli/integ/e2e/ec2_task_test.go, ecs-cli/integ/e2e/fargate_service_test.go
This commit removes the t.Parallel() call which marks tests as
parallelizable from ec2_task_test and fargate_service_test. This change
resolves an ABA which resulted from conflicting calls to testConfig in 
integ/cmd/configure.go
----
**Testing**
- [✅] Unit tests passed
- [✅ ] Integration tests passed
- [ n/a] Unit tests added for new functionality
- [n/a ] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
- [✅ ] Link to issue or PR for the integration tests:
- [ n/a] Contacted our doc writer
- [n/a ] Updated our README
----
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Remove parallelization of e2e tests to resolve config race condition

ecs-cli/modules/utils/compose/convert_task_definition.go, ecs-cli/modules/utils/compose/convert_task_definition_test.go, ecs-cli/modules/utils/compose/ecs_params_reader.go, ecs-cli/modules/utils/compose/ecs_params_reader_test.go
Previously when sending certain requests that contain optional fields to ECS through the Go AWS SDK, we always send empty strings instead of nil for those optional fields that are not set. The service treats such an action as an explicit intent and hence fails to plug in the default values from the service side.
This PR closes #927. Specifically, the repo 3.
----
**Testing**
I was able to run `ecs-cli compose service up` instead of getting the `named volume [backup-laptop] is used but no declaration was found in the volumes section` error message described in the issue. Also verified the default, "local" driver, was correctly set on the service side in task def:
``` …
```
=> Send optional fields as nil instead of "" to ECS

Makefile
Updated Makefile to use docker Go 1.12 as per CONTRIBUTING instructions
Fixes https://github.com/aws/amazon-ecs-cli/issues/956
----
```sh
$ make docker-build
docker run -v **redacted**/amazon-ecs-cli:/usr/src/app/src/github.com/aws/amazon-ecs-cli \
--workdir=/usr/src/app/src/github.com/aws/amazon-ecs-cli \
--env GOPATH=/usr/src/app \
--env ECS_RELEASE= \
golang:1.12 make bin/linux-amd64/ecs-cli
Unable to find image 'golang:1.12' locally
1.12: Pulling from library/golang
16ea0e8c8879: Pull complete 
50024b0106d5: Pull complete 
ff95660c6937: Pull complete 
9c7d0e5c0bc2: Pull complete 
2a19d2e6789c: Pull complete 
1b21789f9965: Pull complete 
a5831c4ee599: Pull complete 
Digest: …
```
=> update Makefile to use docker Go 1.12

ecs-cli/modules/cli/local/network/setup.go
The local endpoints container always uses default credentials. This PR takes the AWS_PROFILE environment variable, if set and uses that otherwise uses `default` as the AWS_PROFILE used by the local endpoints container. This is needed as when we run locally, our users assume a role for virtually every task and default creds are typically the users keys which do not have the permissions to make any calls that the local endpoints container needs.
Addresses #962 
----
**Testing**
- …
=> using AWS_PROFILE if set for local endpoints container

buildspec.yml
Our internal cli release pipeline has been failing due to:
```
if [ "$VERSION" != "v$CHECKED_IN_VERSION" ]; then 
echo "the VERSION file contains a version number that is different from the git tag. file: $CHECKED_IN_VERSION, tag: $VERSION"   
exit 1 
fi 
the VERSION file contains a version number that is different from the git tag. file: 1.18.0, tag:  
[Container] 2019/12/19 23:45:15 Command did not exit successfully
```
The culprit is it tries to compare the checked in version file with the git tag of the current commit when it's actually not being tagged at all. This is the case for all non-release commits. This PR changes the it to only validate against the checked-in version string when the current commit is indeed tagged.
N/A
----
Enter `[N/A]` in the box, if an item is not …
=> Only compare with the checked in version string if the commit is tagged

ecs-cli/modules/cli/local/converter/converter.go, ecs-cli/modules/cli/local/converter/converter_test.go, ecs-cli/modules/cli/local/converter/override.go, ecs-cli/modules/cli/local/converter/override_test.go, ecs-cli/modules/cli/local/localproject/project.go, ecs-cli/modules/commands/flags/flags.go, ecs-cli/modules/commands/local/local_command.go
Looks for a TaskRole and sets that as the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable. Also deletes the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` from the `docker-compose.ecs-local.override.yml` as this is not necessary and will always override this setting
Fixes #969
----
**Testing**
----
=> fixing local create to use taskRole

buildspec_integ.yml
The default behavior for CodeBuild is to check out the master branch and run the canary from there. However, for canary we would like it to run based of the latest release.
----
**Testing**
----
##Manual testing
Modified the buildspec_integ.yml and use the ecs-cli-on-demand-integ-test CodeBuild project to test run the integ tests just like what our canary does. And it started successfully with the right tagged commit:
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Updated the canary buildspec to check out the latest release

ecs-cli/Gopkg.lock, ecs-cli/Gopkg.toml, ecs-cli/vendor/github.com/docker/cli/cli/compose/loader/interpolate.go, ecs-cli/vendor/github.com/docker/cli/cli/compose/loader/loader.go, ecs-cli/vendor/github.com/docker/cli/cli/compose/loader/windows_path.go
Fixes #978 to more clearly specify the `docker/cli` dependency constraint
This change specifies to use any patch from `18.09.x` and includes the `Gopkg.*` and `vendor/` files to match.
My thoughts on this below. 🧐
The Docker projects often do **not** use SemVer. Instead, they use a `YY.MM.patch` approach as documented https://www.docker.com/blog/docker-enterprise-edition/. This is true for this `docker/cli` dependency and others like `docker/docker`
Refer to issue #978 for diagnostic details. In addition to those diagnostics...
The `vendor/` files for this `docker/cli` dependency that were commited months ago to this repo are from `18.09.5`. This was verified with two methods: 1) `Gopkg.lock` declares the specific version and commit it locked; 2) `git diff` showed no changed files when I …
=> update docker/cli dependency constraint

CONTRIBUTING.md, Makefile
fixes https://github.com/aws/amazon-ecs-cli/issues/977
* sets `go dep` version to 0.5.4, which is the version actually being used (see issue for details)
* parameterized the `go` version in the Makefile, saw oft churn on it, and brings in alignment with how dep's version is already managed
**Testing**
Manual testing also done to verify both the two changes listed at the top.
`make generate-deps` generated the following output. Demonstrating the updated dep version 0.5.4 was successfully used and installed.
```yaml
make …
```
=> set go dep version to actual; paramiz go version

ecs-cli/integ/cmd/down.go, ecs-cli/integ/e2e/fargate_service_test.go
We were seeing services and empty clusters being left over when UpdateService was being called immediately after CreateService, due to eventual read consistency issues in ECS, mostly on the `TestCreateClusterWithFargateService` integration test.. This would cause the UpdateService call to fail, which meant the cleanup actions (DeleteService, DeleteCluster) were not getting called. This ensures they will be even if intermediate calls inside the test function fail.
----
=> Defer resource cleanup in integ test

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_helper.go, ecs-cli/modules/cli/compose/entity/service/service_test.go
Previously, we would first call CreateService with desired count 0 then
call UpdateService to set the desired count to 1. This eliminates extra
API calls, as well as the need to wait until the service is describable
before "starting" it.
Note: This effectively reverts 264fe13
Related: #79
----
**Testing**
----
=> fix: "compose service up" sets desired count to 1

ecs-cli/integ/cmd/up.go, ecs-cli/integ/e2e/fargate_service_test.go, ecs-cli/modules/cli/compose/entity/entity_helper.go, ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_helper.go, ecs-cli/modules/cli/compose/entity/service/service_test.go
Previously, calling createTask without any waiters would cause the
integration tests to fail since we depend on eventual consistency to
make assertions on the state of the service. There were issues with the
DescribeService calls being made hitting different DB replicas, causing
the integration tests to be brittle. This keeps the change that combines
the API calls on `compose service up` for a new service, while also
ensuring that the service gets to a stable state before further action.
This also adds an identifier prefix on the name of the service being
launched by the TestCreateClusterWithFargateService integ test.
----
**Testing**
- [ N/A] Updated our README
---- …
=> fix: add waiters to create task

ecs-cli/integ/e2e/fargate_service_test.go
Previous fix in 26c7177e did not ensure cleanup of the service if the
TestServiceUp call failed. This would lead to situations in which
cluster deletion would fail in the TestCreateClusterWithFargateService
integration test because the cluster still contained an "active" service.
----
**Testing**
----
=> fix: ensure cleanup of service

README.md
Adds a little blurb about the ECS CLI v2 in the Readme. 
Feel free to poke around here: https://github.com/kohidave/amazon-ecs-cli
----
**Testing**
----
=> Add ECS CLI V2 link in README.md

buildspec_canary.yml, buildspec_integ.yml, buildspec_verify.yml, scripts/verify.sh
Adds integ test stage in parallel with build stage which runs "make integ"
Adds verification stage after release which uses the following logic: 
* Download artifacts from cn-north-1 endpoint 
* Download signatures from US endpoint
* If signature mismatch, or unable to download artifact, retry in 15 minutes
* Repeat until 8 hour codebuild project timeout.  
----
**Testing**
- [x ] Unit tests passed
- [x ] Integration tests passed
----
=> fix(pipeline): Add verification step and integ tests to pipeline

ecs-cli/integ/e2e/fargate_service_test.go, ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_helper.go, ecs-cli/modules/clients/aws/ecs/client.go, ecs-cli/modules/utils/sleeper.go, ecs-cli/modules/utils/waiters/waiters.go
This eliminates the extra UpdateService call we currently make to scale a service down to 0 before deleting, and should therefore mitigate eventual read consistency errors that occur on updates during describe calls.
Also includes refactor of service waiter to get rid of unused argument.
----
**Testing**
----
=> fix: add force flag to ECSClient#DeleteService

ecs-cli/modules/cli/cluster/cluster_app.go, ecs-cli/modules/cli/cluster/cluster_app_test.go, ecs-cli/modules/clients/aws/cloudformation/cluster_template.go
CloudFormation will try to validate the Default ECSInstanceType parameter
based on the AllowedValues field which is problematic in regions that do
not support our default t2.micro instance type such as eu-north-1.
Resolves #1006
----
**Testing**
----
=> Validate instance type before CloudFormation

ecs-cli/modules/cli/local/secrets/clients/clients.go, ecs-cli/modules/cli/local/secrets/clients/clients_test.go, ecs-cli/modules/cli/local/secrets/secrets_test.go
Addresses #1010 and #1011. 
This change solves an error where we did not extract
fully qualified paths (/path/to/param) from SSM parameter ARNS
containing nested hierarchical param names. We would instead grab
"path/to/param" (excluding the leading "/") and attempt to call GetParameter via the AWS SDK,
which would result in a failure and an incorrect error message.
More information on SSM parameter name constraints [here].(https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-parameter-name-constraints.html)
----
**Testing**
- [ in progress] Integration tests passed
----
=> fix(cli): Fix incorrect parsing of ARNs w/ nested param names

buildspec.yml, buildspec_integ.yml
Buildspec.yml now copies all files to the gopath and works from there, not the codebuild source directory. 
Buildspec_integ.yml does not set the GOPATH, GOROOT, or GOCACHE before building the test binary. This was causing a conflict with goenv and the shim-based go versioning used in standard images >=2.0. 
Prerequisite work for version 1.19.0
This change introduces a failure (only in Codebuild on AWS) of one unit test, perhaps related to an environment variable being set unexpectedly in the build image.
```
607 | --- FAIL: TestNewCommandConfigFromEnvVarsWithRegionNotSpecified (0.00s)
--
608 | command_config_test.go:86:
609 | Error Trace:    command_config_test.go:86
610 | Error:          An error is expected but got nil.
611 | Test: …
```
=> Update buildspecs to work with dep & codebuild standard 4.0

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go
Checks the launchtype before setting platform version. This reverts a breaking change in compose service up introduced in 1.19.0. 
Addresses issue #1040 
----
**Testing**
- [ x] Unit tests passed
- [... ] Integration tests passed
----
=> Add launchtype check before setting platform version

.mergify.yml
Allow a quick way of stopping mergify from auto-merging PRs that need to wait for some reason
---
=> chore: don't merge when the do-not-merge or WIP labels are applied

.github/ISSUE_TEMPLATE/---feature-request.md
Adds checkbox for person reporting issue to indicate they may be able to
contribute.
--- 
=> chore: update feature request template

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go, ecs-cli/modules/cli/compose/entity/task/task.go, ecs-cli/modules/cli/compose/entity/task/task_test.go, ecs-cli/modules/config/command_config.go
Picks up from #1056 and adds tests, additional safety check for launch type, and adds test helper function to task_test.go. 
Addresses #1043 
----
**Testing**
- [n/a] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
----
=> feat(compose): Add EFS support for task workflows

ecs-cli/modules/cli/compose/entity/service/service.go, ecs-cli/modules/cli/compose/entity/service/service_test.go
Previously, running `ecs-cli compose service up` on an already existing service and specifying the flags --enable-service-discovery would result in errors. 
This was bad behavior, as commands are sometimes scripted without respect to the status of the service and we should offer idempotency in this case when possible.
This PR adjusts the behavior when the service already exists to display warning messages and continue, ignoring those flags, instead of failing. 
Addresses #1069 
----
**Testing**
- [n/a] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
- [n/a ] Link to issue or PR for the integration tests:
----
By submitting this …
=> fix(service): Replace errors from invalid compose service up flags with warnings
