aws/amazon-ecs-cli

- ecs-cli/modules/config/ami/ami.go
Got these from http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
This should fix #56.
> Update AMIs from 2015.09.b to 2015.09.c.

- ecs-cli/modules/aws/clients/ecs/client.go
- ecs-cli/modules/aws/clients/ecs/mock/client.go
- ecs-cli/modules/compose/cli/ecs/app/factory.go
- ecs-cli/modules/compose/cli/ecs/app/service_command.go
- ecs-cli/modules/compose/ecs/context.go
- ecs-cli/modules/compose/ecs/entity.go
- ecs-cli/modules/compose/ecs/flags.go
- ecs-cli/modules/compose/ecs/project.go
- ecs-cli/modules/compose/ecs/service.go
- ecs-cli/modules/compose/ecs/service_test.go
- ecs-cli/modules/compose/ecs/task.go
Adds 2 deployment parameters to compose service commands that control how many tasks run during the deployment and the ordering of stopping and starting tasks.
For more details about the deployment parameters, check out: 
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_paramters.html
Options:
* --deployment-max-percent
* --deployment-min-healthy-percent
Commands:
* ecs-cli compose service create
* ecs-cli compose service up
* ecs-cli compose service scale
TESTING:
$ make test
PASS
Manual test:
1. Incorrect input to flags
```
$ ./bin/local/ecs-cli compose service create --deployment-min-healthy-percent something
ERRO[0000] Unable to open ECS Compose Project            error=Please pass integer value for the flag deployment-min-healthy-percent
FATA[0000] Unable …
```
> Add deployment configuration to compose service commands

- ecs-cli/modules/compose/ecs/utils/convert_task_definition.go
- ecs-cli/modules/compose/ecs/utils/convert_task_definition_test.go
$ make build
$ ./bin/local/ecs-cli compose up
WARN[0000] Skipping unsupported YAML option...           option name=volumes
WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=build service name=web
WARN[0000] Skipping unsupported YAML option for service...  option name=cap_add service name=web
WARN[0000] Skipping unsupported YAML option for service...  option name=cap_drop service name=web
WARN[0000] Skipping unsupported YAML option for service...  option name=cpuset service name=web
WARN[0000] Skipping unsupported YAML option for service...  option name=cpu_quota service name=web
WARN[0000] Skipping unsupported YAML option for service...  option name=cgroup_parent service name=web
WARN[0000] …
> Add warning for unsupported compose yaml fields

- ecs-cli/modules/compose/ecs/utils/convert_task_definition.go
- ecs-cli/modules/compose/ecs/utils/convert_task_definition_test.go
Compose supports volumes_from with access mode. See [here](https://docs.docker.com/compose/compose-file/#/volumes-from) for details.
If compose file had the option:
```
volumes_from:
- webserver:rw
```
ecs would return an error: volumesFrom.sourceContainer contains invalid characters
Add parsing logic to support the different formats
```
Compose file format v2:
volumes_from:
- service_name
- service_name:ro
- container:container_name
- container:container_name:rw
Compose file format v1:
volumes_from:
- service_name
- service_name:ro
- container_name
- container_name:rw
```
$ make test
PASS
$ make build
```
compose yml excerpt:
volumes_from:
- webserver:rw
```
$ ./bin/local/ecs-cli compose up
INFO[0000] Using ECS task definition …
> Parse different volumes_from format supported by compose.

- ecs-cli/modules/command/cluster_app.go
- ecs-cli/modules/command/cluster_app_test.go
closes #52 
closes #65
closes #154
closes #163
```sh
$ make build
Built ecs-cli
```
```sh
$ make test
PASS
coverage: 61.9% of statements
ok  	github.com/aws/amazon-ecs-cli/ecs-cli/modules/command	0.016s	coverage: 61.9% of statements
```
```sh
$ ./bin/local/ecs-cli up --keypair *** --capability-iam --vpc vpc-****--subnets subnet-****,subnet-**** --security-group sg-****,sg-****                                            
ERRO[0000] Error executing 'up': You can only specify one security group with the '--security-group' flag
```
```sh
$ ./bin/local/ecs-cli up --keypair *** --capability-iam --vpc vpc-****                                          
ERRO[0000] Error executing 'up': You have selected a VPC. Please specify 2 …
```
> Cluster up security group, vpc, subnets, azs validations

- ecs-cli/modules/command/image_app.go
- ecs-cli/modules/command/image_app_test.go
closes https://github.com/aws/amazon-ecs-cli/issues/238
```
$ make build
$ make test
$  ./bin/local/ecs-cli push busybox:0.0.1-alpha15-BOTS-11-ge426894-b18
```
> Bug fix: allow dashes in ecs-cli push

- ecs-cli/modules/cli/cluster/cluster_app_test.go
- ecs-cli/modules/cli/configure/configure_test.go
- ecs-cli/modules/config/config_test.go
- ecs-cli/modules/config/destination_test.go
- ecs-cli/modules/config/params_test.go
This is the first commit of PR https://github.com/aws/amazon-ecs-cli/pull/242
> Use assert in cluster, config, and params tests

- ecs-cli/modules/cli/compose/entity/service/service.go
- Add warning message when user attempts to modify the LB configuration of
an existing service
> Log warning message when trying to update LB

- ecs-cli/modules/cli/cluster/cluster_app_test.go
- ecs-cli/modules/cli/compose/factory/factory_test.go
- ecs-cli/modules/cli/image/image_app_test.go
- ecs-cli/modules/clients/aws/ecs/client_test.go
- ecs-cli/modules/commands/cluster/cluster_command.go
- ecs-cli/modules/commands/compose/compose_command.go
- ecs-cli/modules/commands/compose/service/compose_service_command.go
- ecs-cli/modules/commands/flags.go
- ecs-cli/modules/commands/image/image_command.go
- ecs-cli/modules/config/config_test.go
- ecs-cli/modules/config/config_v1.go
- ecs-cli/modules/config/params.go
- ecs-cli/modules/config/params_test.go
- ecs-cli/modules/config/readwriter.go
- ecs-cli/modules/config/readwriter_v1.go
- ecs-cli/modules/config/readwriter_v1_test.go
- Read from config and credentials file
- Flags determine which profile and which cluster configuration are used
> Reading from the new configs

- ecs-cli/modules/config/ami/ami.go
- Ran `ecs-cli up` in every single region that ecs supports. Checked that the agent is connected.
> Update AMI to amzn-ami-2017.03.e-amazon-ecs-optimized

- scripts/publish-functions.sh
- scripts/publish-staged
- Bug was introduced when I made the changes to the scripts to allow releasing to cn-north-1; I didn't realize that the function s3_cp was used in the staging script as well.
> Fixed a bug in publishing scripts.

- proposals/multi-cluster-config.md
Adds a proposal document for multiple clusters configuration.
Related to #59, #71, #112, #152, #174, #176
Related to proposal https://github.com/aws/amazon-ecs-cli/pull/252
> Add proposal for Multiple clusters configuration

- CONTRIBUTING.md
Also adds instructions for regenerating mocks
> Update instructions for updating dependencies

- proposals/remove-prefix-from-config.md
Adds a proposal document for removing prefixes from config.
Related to proposal https://github.com/aws/amazon-ecs-cli/pull/251
> Add proposal for removing prefixes from config

- ecs-cli/modules/cli/configure/configure.go
- ecs-cli/modules/cli/configure/migrate.go
- Migrate command only creates a credential file if keys are present in the old configuration file.
```
$ ecs-cli configure migrate
Old configuration file
-----------------------------------------------------
~/.ecs/config
[ecs]
cluster                     = INSERT-CLUSTER-NAME-HERE
aws_profile                 = profile
region                      = us-east-2
aws_access_key_id           =
aws_secret_access_key       =
compose-project-name-prefix = ecscompose-
compose-service-name-prefix = ecscompose-service-
cfn-stack-name-prefix       = amazon-ecs-cli-setup-
New configuration files
-----------------------------------------------------
~/.ecs/config
version: v1
default: default
cluster-configurations:
default:
cluster: INSERT-CLUSTER-NAME-HERE
region: us-east-2 …
```
> [Bugfix] Migrate command

- CONTRIBUTING.md
Adding the Amazon Open Source Code of Conduct text to the CONTRIBUTING.md file.
> Amazon Open Source Code of Conduct text addition

- ecs-cli/modules/clients/aws/cloudformation/template.go
> [BUGFIX] Fix CFN template for creating Instance Profile

- ecs-cli/Godeps/Godeps.json
- ecs-cli/modules/clients/aws/ec2/mock/sdk/ec2iface_mock.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/config.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/version.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/api.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecr/api.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/doc.go
- ecs-cli/vendor/github.com/aws/aws-sdk-go/service/sts/api.go
- Updated aws-sdk-go in $GOPATH dir
- Deleted aws-sdk-go from Godeps.json
- Deleted aws-sdk-go vendor files
- From ecs-cli dir, ran godep save ./...
- Ran $ make generate
> Update aws-sdk-go to 1.12.58 (with health check grace period support)

- ecs-cli/modules/cli/cluster/cluster_app.go
- ecs-cli/modules/cli/cluster/cluster_app_test.go
- ecs-cli/modules/commands/cluster/cluster_command.go
- ecs-cli/modules/commands/flags/flags.go
Also adds confirmation step for deleting cluster with no cloudformation
stack.
> Allow cluster up with empty cluster

- ecs-cli/modules/cli/compose/container/container.go
- ecs-cli/modules/cli/compose/context/context.go
- ecs-cli/modules/cli/compose/entity/task/task_test.go
- ecs-cli/modules/cli/compose/project/project_test.go
- ecs-cli/modules/cli/image/image_app.go
- ecs-cli/modules/cli/logs/logs_app.go
- ecs-cli/modules/clients/aws/cloudformation/client.go
- ecs-cli/modules/clients/aws/ecr/client.go
- ecs-cli/modules/clients/docker/client.go
- ecs-cli/modules/config/config_v1.go
- ecs-cli/modules/config/readwriter_v1.go
- ecs-cli/modules/utils/cache/fs_cache.go
- ecs-cli/modules/utils/cache/noop_cache.go
- ecs-cli/modules/utils/compose/convert_task_definition.go
- ecs-cli/modules/utils/compose/ecs_params_reader_test.go
To appease the report card gods:
https://goreportcard.com/report/github.com/aws/amazon-ecs-cli
> Fix spelling and lint errors

- ecs-cli/modules/config/ami/ami.go
Also used map literal instead of make, for artistic reasons
> Add AMI id for Gov Cloud

- ecs-cli/modules/utils/compose/convert_task_definition.go
- ecs-cli/modules/utils/compose/convert_task_definition_test.go
Previously, the check for the "networks" field was based on the
NetworkConfigs attribute on the project to be empty. Libcompose changed
the behavior of the Parse method to always create a "default" network
config (See: https://github.com/docker/libcompose/commit/18dad7cb).
This caused a lot of spurious warnings for customers when they would try
to run a task even if the networks field was not specified in their
docker-compose files.
Fixes #406 and closes #237
> Fix YAML parse warning on networks field

- ecs-cli/modules/clients/aws/cloudformation/template.go
> Support longer resource IDs in CFN template

- ecs-cli/modules/cli/compose/project/project.go
- ecs-cli/modules/cli/compose/project/project_parseV1V2.go
- ecs-cli/modules/cli/compose/project/project_parseV3.go
- ecs-cli/modules/cli/compose/project/project_test.go
- ecs-cli/modules/cli/compose/project/project_version.go
- ecs-cli/modules/cli/compose/project/project_version_test.go
> Add compose version check

- ecs-cli/modules/cli/compose/containerconfig/containerconfig.go
> Update ContainerConfig to accomodate fields supplied by compose 3

- ecs-cli/modules/cli/compose/containerconfig/containerconfig.go
In preparation for parseV1V2 conversion
> Update ContainerConfig types

- ecs-cli/modules/utils/compose/convert_task_definition.go
> Fix style warnings in convert_task_definition

- ecs-cli/modules/cli/compose/project/project.go
- ecs-cli/modules/utils/compose/convert_task_definition.go
- ecs-cli/modules/utils/compose/convert_task_definition_test.go
- ecs-cli/modules/utils/utils.go
- ecs-cli/modules/utils/utils_test.go
> Add support for named volumes.

- ecs-cli/modules/cli/compose/containerconfig/containerconfig.go
- ecs-cli/modules/cli/compose/project/project_parseV3.go
- ecs-cli/modules/cli/compose/project/project_parseV3_test.go
> Set most v3 fields on ContainerConfig, add tests

- ecs-cli/modules/cli/compose/project/project_parseV3.go
Test output (task def creation error expected ATM):
Docker file:
```yaml
version: '3'
services:
web:
command: echo "hello world"
deploy:
mode: replicated
```
Output:
```
$> ..\..\Documents\GO\src\github.com\aws\amazon-ecs-cli\bin\local\ecs-cli.exe compose create
WARN[0000] Skipping unsupported YAML option for service...  option name=deploy service name=web
ERRO[0000] Unable to open ECS Compose Project            error="cannot create a task definition with no containers; invalid service config"
FATA[0000] Unable to create and read ECS Compose Project  error="cannot create a task definition with no containers; invalid service config"
```
Docker file:
```yaml
version: '3'
services:
web:
command: echo "hello world"
deploy:
resources:
limits:
cpus: '0.5'
memory: 50M
```
Output:
```
$> …
```
> Log warning if deploy key is found in compose project

- ecs-cli/modules/utils/compose/convert_task_definition.go
- ecs-cli/modules/utils/compose/convert_task_definition_test.go
test docker-compose:
```
version: '2'
services:
wordpress:
image: wordpress
cpu_shares: 55
mem_limit: 20MB
mem_reservation: 15MB
ports:
- "80:80"
links:
- mysql
logging:
driver: awslogs
options: 
awslogs-group: multiservice-wordpress
awslogs-region: us-east-1
awslogs-stream-prefix: wordpress
mysql:
image: mysql
mem_limit: 20MB
environment:
MYSQL_ROOT_PASSWORD: password
logging:
driver: awslogs
options: 
awslogs-group: multiservice-mysql
awslogs-region: us-east-1
awslogs-stream-prefix: mysql
```
test ecs-params.yml:
```
version: 1
services:
wordpress:
essential: true
cpu_shares: 102
mem_limit: 30g
mem_reservation: 22m
```
test output for overriding:
```
$~\multiService> ..\..\Documents\GO\src\github.com\aws\amazon-ecs-cli\bin\local\ecs-cli.exe compose create
INFO[0000] …
```
> Merge ecs-params service resources with task def values

- ecs-cli/modules/cli/compose/context/ecs_context.go
- ecs-cli/modules/cli/compose/logger/logger.go
- ecs-cli/modules/cli/compose/project/project.go
- ecs-cli/modules/cli/compose/project/project_parseV1V2.go
- ecs-cli/modules/cli/compose/project/project_test.go
- ecs-cli/modules/utils/compose/convert_task_definition.go
- ecs-cli/modules/utils/compose/convert_task_definition_test.go
- ecs-cli/modules/utils/value/value.go
Opened in place of https://github.com/aws/amazon-ecs-cli/pull/524 (rebased on latest)
> Move logging unsupported fields into logger package

- ecs-cli/modules/cli/compose/project/project_parseV3.go
- ecs-cli/modules/cli/compose/project/project_parseV3_test.go
`make` and `make test` succeed
compose execution & output:
```
$~\oneServUlimits> ..\..\Documents\GO\src\github.com\aws\amazon-ecs-cli\bin\local\ecs-cli.exe compose create
INFO[0000] Using ECS task definition                     TaskDefinition="oneServUlimits:1"
```
test docker-compose.yml with v3 & ulimits:
```
version: '3'
services:
web:
image: httpd
ports:
- "80:80"
ulimits:
nice: 6505
rss:
soft: 2000
hard: 4000
```
output task definition:
```
{
{
"portMappings": [
{
"hostPort": 80,
"protocol": "tcp",
"containerPort": 80
}
],
"cpu": 0,
"ulimits": [
{
"name": "rss",
"softLimit": 2000,
"hardLimit": 4000
},
{
"name": "nice",
"softLimit": 6505,
"hardLimit": 6505
}
],
"memory": 512,
"memoryReservation": null,
"image": "httpd",
"essential": true,
"name": "web"
}
], …
```
> Add ulimits to parseV3

- ecs-cli/modules/clients/user_agent.go
> Add prefix 'aws' to user agent string

- README.md
Add ecs-params service resource fields to README
--
> Add ecs-params service resource fields to README

- ecs-cli/modules/utils/compose/convert_task_definition.go
- ecs-cli/modules/utils/compose/convert_task_definition_test.go
Also some cleanup/reordering in tests
> Fix log message for resource overrides

- ecs-cli/modules/cli/compose/entity/task/task.go
- ecs-cli/modules/clients/aws/ecs/client.go
- ecs-cli/modules/clients/aws/ecs/client_test.go
- ecs-cli/modules/clients/aws/ecs/mock/client.go
> Refactor ECSClient#RunTask

- ecs-cli/modules/utils/compose/ecs_params_reader.go
- ecs-cli/modules/utils/compose/ecs_params_reader_test.go
> Service Discovery: Add ECS Params schema

- README.md
> Clarify task placement docs

- README.md
> Add Healthcheck to README

- ecs-cli/modules/cli/compose/project/project_parseV3.go
- ecs-cli/modules/cli/compose/project/project_parseV3_test.go
> Add nil check for env var values

- .github/ISSUE_TEMPLATE.md
> Fix Issue template

- ecs-cli/modules/cli/servicediscovery/servicediscovery_app.go
- ecs-cli/modules/cli/servicediscovery/servicediscovery_app_test.go
- ecs-cli/modules/cli/servicediscovery/servicediscovery_helper.go
> Ensure CFN Stack Names fit API length and charset requirements

- .travis.yml
- CONTRIBUTING.md
- Makefile
> Support go 1.11

- ecs-cli/modules/cli/logs/logs_app.go
- decreased sleep time from 30 to 10 seconds for the --follow option
- removed recursion from code and replaced with a loop
- added error handling on the API call
- fixes #612
> Improved logs command

- proposals/awslogs.md
Added proposal for new commands to retrieve and configure container logs in CloudWatch.
> Proposal: Retrieve Container Logs from CloudWatch

- README.md
> README for Service Discovery

- ecs-cli/modules/cli/servicediscovery/servicediscovery_app.go
- ecs-cli/modules/cli/servicediscovery/servicediscovery_app_test.go
- On create, If CLI detects that a CFN stack already exists, it tries to delete it
- For namespaces, it only does force recreation if the namespace could not be found using route53 servicediscovery APIs
- This features allows the CLI to clean up old CFN stacks from previous failed attempts
- Route53 will prevent the removal of any resource that is actually in use
> Force-recreate for service discovery resources

- ecs-cli/modules/cli/compose/entity/service/service.go
- ecs-cli/modules/commands/compose/service/compose_service_command.go
> Clarify help text for load balancer flags

- README.md
> Add README content for using private reg creds

- README.md
- ecs-cli/modules/cli/compose/entity/entity_helper.go
- ecs-cli/modules/utils/compose/convert_task_definition.go
- ecs-cli/modules/utils/compose/convert_task_definition_test.go
- ecs-cli/modules/utils/compose/ecs_params_reader.go
- ecs-cli/modules/utils/compose/ecs_params_reader_test.go
If at first you don't succeed, try again.
> Redo: support pidMode and ipcMode in ECS Params.

- ecs-cli/main.go
- ecs-cli/modules/utils/logger/logger.go
> Ensure that logger writes to stdout

- ecs-cli/modules/commands/compose/service/compose_service_command.go
> Fix Service Discovery Flag description

- ecs-cli/modules/cli/compose/entity/service/service.go
- ecs-cli/modules/cli/compose/entity/service/service_test.go
- ecs-cli/modules/clients/aws/ecs/client.go
- ecs-cli/modules/clients/aws/ecs/mock/client.go
See `cd98949`
Includes refactors to service test to remove unnecessary helpers/mocks.
> Update service refactor

- ecs-cli/modules/commands/compose/service/compose_service_command.go
> Improve Service Discovery flag help text

- ecs-cli/modules/cli/compose/entity/service/service.go
- ecs-cli/modules/cli/compose/entity/service/service_test.go
Add tags when updating an existing service.
> Tag services on update

- README.md
> Added tagging to README

- buildspec.yml
Add buildspec.yml to support CodeBuild integration
--
> Add buildspec

- README.md
For some reason these changes disappeared before the merge to dev....
> Tagging readme - again

- README.md
> Add gpu to ECS parameters in the README

- README.md
> Add link to supported compose fields, ecs-params memory units to README

- README.md
> Add security disclosures notice

- ecs-cli/modules/cli/local/down_app.go
> fixed #792: time out error when down --all

- ecs-cli/modules/cli/local/down_app.go
> add timeout watch for listing filtered containers

- ecs-cli/modules/cli/local/down_app.go
> fixed bug: time out error when down --all

- ecs-cli/modules/cli/compose/entity/entity_helper.go
- ecs-cli/modules/cli/local/converter/converter.go
- ecs-cli/modules/cli/local/converter/converter_test.go
- ecs-cli/modules/cli/local/localproject/project.go
- ecs-cli/modules/cli/local/localproject/project_test.go
Also refactored metadata logic
Addresses #810 
----
**Testing**  
----
> [local] Add ipc/pid fields

- ecs-cli/modules/cli/local/converter/converter.go
Related: https://github.com/aws/amazon-ecs-cli/issues/804
> Add comment about port conversion

- ecs-cli/modules/cli/local/localproject/project.go
- ecs-cli/modules/clients/aws/secretsmanager/client.go
GetSecretValue is implemented directly in the local/secrets/clients package.
----
> Remove unused secrets methods

- ecs-cli/integ/e2e/local_test.go
- ecs-cli/modules/cli/local/converter/converter.go
- ecs-cli/modules/cli/local/converter/converter_test.go
- ecs-cli/modules/cli/local/localproject/project.go
- ecs-cli/modules/commands/local/local_command.go
> Rename default output file

- ecs-cli/modules/cli/local/converter/converter.go
Issue #, if available:
#800 
Description of changes:
Warn if aws logging is set in task definition.
----
**Testing**  
----
> [local] added warning for not supporting aws logging

- ecs-cli/modules/cli/local/converter/converter.go
Fixes #861 
----
**Testing**  
----
> Cleanup log messages for pid/ipc fields

- ecs-cli/modules/cli/local/down_app.go
- ecs-cli/modules/cli/local/options/options.go
- ecs-cli/modules/cli/local/ps_app.go
Fixes #859
----
**Testing**  
----
> Show task definition path in log message for ps and down

- README.md
**Description of changes**: Fill the `local ps` and `local down` subcommands in the README.
Partially addresses #811 
----
**Testing**  
----
> Add explanation for local ps and local down

- README.md
> Add local up/create to README

- ecs-cli/modules/cli/local/converter/converter.go
- ecs-cli/modules/cli/local/create_app.go
- ecs-cli/modules/cli/local/localproject/project.go
- ecs-cli/modules/cli/local/ps_app.go
- ecs-cli/modules/cli/local/up_app.go
Clean up code,  adjust some formats, and fix small issues.
----
**Testing**  
----
> Code cleanup and some format adjustments

- Makefile
Reverts aws/amazon-ecs-cli#887
> Revert "update MAKE target integ-test-run-with-coverage"

- Makefile
> Update MAKE target integ-test-run-with-coverage

- ecs-cli/modules/commands/attributechecker/attribute_checker_command.go
- ecs-cli/modules/commands/cluster/cluster_command.go
- ecs-cli/modules/commands/compose/compose_command.go
- ecs-cli/modules/commands/compose/service/compose_service_command.go
- ecs-cli/modules/commands/configure/configure_command.go
- ecs-cli/modules/commands/image/image_command.go
- ecs-cli/modules/commands/license/license_command.go
- ecs-cli/modules/commands/local/local_command.go
- ecs-cli/modules/commands/log/logs_command.go
- ecs-cli/modules/commands/regcreds/regcreds_command.go
- ecs-cli/modules/commands/usage/usage.go
Puts docs for command usage in one place for ease of editing and to facilitate greater consistency in documentation.
----
> Refactor usage

- CONTRIBUTING.md
> Update go version

- README.md
- ecs-cli/modules/cli/local/localproject/project.go
- ecs-cli/modules/cli/local/localproject/project_test.go
- ecs-cli/modules/commands/local/local_command.go
Fixes #848 
----
**Testing**
----
> Add force flag to local up/create

- ecs-cli/integ/e2e/local_test.go
Adds three new integration tests in integ/e2e/local_test.go, specifically targeting local up, local create, and local down. Removes t.Parallel() call from TestECSLocal(...) to stop these new tests from interfering with clean state tests. 
Adds a method createLocalTaskDefFile(...) to local_test which is repeatedly invoked to create a temporary task-definition.json file for each new integ test. 
----
**Testing**
- [n/a] Unit tests added for new functionality
- [n/a] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
- [n/a] Link to issue or PR for the integration tests:
- [n/a] Contacted our doc writer
- [n/a] Updated …
> Expanding ecs-cli local integration test coverage (hello world!)

- ecs-cli/modules/cli/compose/entity/entity_helper.go
- ecs-cli/modules/cli/compose/project/project.go
- ecs-cli/modules/cli/compose/project/project_test.go
This PR allows passing placement constraints through ecsParams yaml file to a task definition
Fixes #721
----
**Testing**
- [] Integration tests passed
- [] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
- [] Link to issue or PR for the integration tests:
- [] Contacted our doc writer
- [] Updated our README
----
> Allow passing placement constraints through ecsParams yaml file to a task definition

- buildspec.yml
Uncomment unit tests
N/A
----
**Testing**
----
> Make it actually run the unit tests

- CONTRIBUTING.md
Updating to reflect trunk-based development per https://github.com/aws/amazon-ecs-cli/issues/946
----
**Testing**
----
> Update CONTRIBUTING to specify master branch

- ecs-cli/integ/e2e/local_test.go
* Accounts for changes in #970
----
**Testing**
- [n/a] Unit tests added for new functionality
- [n/a] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
-  https://github.com/aws/amazon-ecs-cli/issues/972
- [n/a] Updated our README
----
> Update integ TestECSLocal to omit /creds in override file

- .travis.yml
- CONTRIBUTING.md
- Makefile
> Update Makefile and travis.yml to include GO 1.13

- ecs-cli/modules/utils/utils.go
- ecs-cli/modules/utils/utils_test.go
https://github.com/aws/amazon-ecs-cli/pull/959 was approved but merged into the dev branch instead of the master branch
N/A
----
**Testing**
----
> Merge approved PR into the right branch

- .travis.yml
> chore: update travis.yml

- ecs-cli/integ/e2e/ec2_task_test.go
> fix: defer resource cleanup for TestCreateClusterWithEC2Task

- README.md
Added this to the `README.md`
```bash
brew install amazon-ecs-cli
```
**Testing**
N/A
----
> Add brew install amazon-ecs-cli

- .mergify.yml
See: https://doc.mergify.io/getting-started.html#configuration
> chore: add mergify config

- .mergify.yml
> temporarily remove codebuild condition from mergify

- .mergify.yml
> chore: automerge dependabot PRs with mergify

- .mergify.yml
- ecs-cli/Gopkg.lock
- ecs-cli/Gopkg.toml
- ecs-cli/modules/cli/compose/entity/service/service.go
- ecs-cli/modules/cli/compose/entity/service/service_test.go
- ecs-cli/modules/cli/compose/entity/task/task.go
- ecs-cli/modules/cli/compose/entity/task/task_test.go
- ecs-cli/modules/config/command_config.go
Merges master into mainline. 
----
**Testing**
----
> chore: Merge master into mainline in preparation for upcoming branch change. 
